function framePlan = buildFramePlan(scenarioPlan, frameId)
%BUILDFRAMEPLAN Resolve one frame window from a frozen ScenarioPlan.

if nargin < 1 || ~isstruct(scenarioPlan) || ...
        ~isfield(scenarioPlan, 'Frame') || ~isstruct(scenarioPlan.Frame)
    error('CSRD:FramePlan:MissingScenarioFrame', ...
        'ScenarioPlan.Frame is required to build a FramePlan.');
end
if nargin < 2 || isempty(frameId) || ~isnumeric(frameId) || ...
        ~isscalar(frameId) || ~isfinite(frameId) || frameId < 1 || ...
        abs(frameId - round(frameId)) > 0
    error('CSRD:FramePlan:InvalidFrameId', ...
        'frameId must be a positive integer scalar.');
end

frame = scenarioPlan.Frame;
localRequirePositiveInteger(frame, 'FrameNumSamples');
localRequirePositiveInteger(frame, 'NumFramesPerScenario');
localRequirePositiveScalar(frame, 'SampleRateHz');
localRequirePositiveScalar(frame, 'FrameDurationSec');

if frameId > frame.NumFramesPerScenario
    error('CSRD:FramePlan:FrameOutOfRange', ...
        'frameId %d exceeds ScenarioPlan.Frame.NumFramesPerScenario=%d.', ...
        frameId, frame.NumFramesPerScenario);
end

frameStartSec = (double(frameId) - 1) * double(frame.FrameDurationSec);
frameEndSec = double(frameId) * double(frame.FrameDurationSec);

framePlan = struct( ...
    'FrameId', double(frameId), ...
    'FrameWindowSec', [frameStartSec, frameEndSec], ...
    'StartTimeSec', frameStartSec, ...
    'EndTimeSec', frameEndSec, ...
    'DurationSec', double(frame.FrameDurationSec), ...
    'FrameNumSamples', double(frame.FrameNumSamples), ...
    'SampleRateHz', double(frame.SampleRateHz), ...
    'ScenarioId', localScenarioId(scenarioPlan), ...
    'Source', 'ScenarioPlan.Frame');
end

function localRequirePositiveInteger(s, fieldName)
localRequirePositiveScalar(s, fieldName);
if abs(double(s.(fieldName)) - round(double(s.(fieldName)))) > 0
    error('CSRD:FramePlan:InvalidFrameContract', ...
        'ScenarioPlan.Frame.%s must be integer-valued.', fieldName);
end
end

function localRequirePositiveScalar(s, fieldName)
if ~isfield(s, fieldName) || isempty(s.(fieldName)) || ...
        ~isnumeric(s.(fieldName)) || ~isscalar(s.(fieldName)) || ...
        ~isfinite(s.(fieldName)) || s.(fieldName) <= 0
    error('CSRD:FramePlan:InvalidFrameContract', ...
        'ScenarioPlan.Frame.%s must be a positive finite scalar.', fieldName);
end
end

function scenarioId = localScenarioId(scenarioPlan)
scenarioId = NaN;
if isfield(scenarioPlan, 'ScenarioId') && isnumeric(scenarioPlan.ScenarioId) && ...
        isscalar(scenarioPlan.ScenarioId)
    scenarioId = double(scenarioPlan.ScenarioId);
end
end
