function assertSegmentSignalReadyForImpairments(segSignal, FrameId, txId, segIdx)
    %ASSERTSEGMENTSIGNALREADYFORIMPAIRMENTS Phase 3 strict check before TX RF chain.
    % Inputs: see signature arguments and local validation.
    % Outputs: see signature return values and contract fields.
    %
    %   csrd.core.ChangShuo.assertSegmentSignalReadyForImpairments( ...
    %       segSignal, FrameId, txId, segIdx)
    %
    %   Hard-checks the segment signal struct that is about to be fed
    %   into the TransmitFactory. The legacy fallbacks (`SampleRate =
    %   2.5 * plannedBW`, `FrequencyOffset = 0`) were removed under
    %   phase-3-construction.md §3.2.B; missing or non-positive values
    %   now raise CSRD:Construction:Missing* identifiers so the
    %   offending modulator / segment builder gets caught at the
    %   source instead of silently producing wrong-rate baseband.
    %
    %   Throws:
    %     * CSRD:Construction:MissingFrequencyOffset
    %     * CSRD:Construction:MissingSampleRate

    if ~isstruct(segSignal)
        error('CSRD:Construction:MissingSegmentSignalStruct', ...
            ['Frame %d, TxID %s, Seg %d: segment signal must be a struct ', ...
             'before transmit impairments; got class ''%s''.'], ...
            FrameId, string(txId), segIdx, class(segSignal));
    end

    if ~isfield(segSignal, 'FrequencyOffset') ...
            || isempty(segSignal.FrequencyOffset) ...
            || ~isnumeric(segSignal.FrequencyOffset) ...
            || ~isscalar(segSignal.FrequencyOffset)
        error('CSRD:Construction:MissingFrequencyOffset', ...
            ['Frame %d, TxID %s, Seg %d: segment lacks a scalar numeric ', ...
             'FrequencyOffset. processSingleSegment must populate it from ', ...
             'ReceiverViews(1).ProjectedCenterOffsetHz; the implicit ''=0'' ', ...
             'fallback was removed in Phase 3.'], ...
            FrameId, string(txId), segIdx);
    end

    if ~isfield(segSignal, 'SampleRate') ...
            || isempty(segSignal.SampleRate) ...
            || ~isnumeric(segSignal.SampleRate) ...
            || ~isscalar(segSignal.SampleRate) ...
            || segSignal.SampleRate <= 0
        error('CSRD:Construction:MissingSampleRate', ...
            ['Frame %d, TxID %s, Seg %d: cannot apply transmit impairments ', ...
             'because the segment SampleRate is missing or non-positive. ', ...
             'Modulators MUST set SampleRate; the ''2.5 x plannedBW'' derive ', ...
             'path was removed in Phase 3.'], ...
            FrameId, string(txId), segIdx);
    end
end
