clc
clear
close all

%%
TimeDuration = 1;
SampleRate = 200e3;
NumTransmitAntennnas = 1;
MasterClockRate = 600e3;

CarrierFrequency = 30e3;
IqImbalanceConfig.A = 3;
IqImbalanceConfig.P = 10;
PhaseNoiseConfig.Level = -50;
PhaseNoiseConfig.FrequencyOffset = 20;
MemoryLessNonlinearityConfig.Method = 'Saleh model';
MemoryLessNonlinearityConfig.InputScaling = 0;
MemoryLessNonlinearityConfig.AMAMParameters = [2.1587 1.1517];
MemoryLessNonlinearityConfig.AMPMParameters =  [4.0033 9.1040];
MemoryLessNonlinearityConfig.OutputScaling = 0;
MemoryLessNonlinearityConfig.ReferenceImpedance = 1;
ThermalNoiseConfig.NoiseTemperature = 290;
AGCConfig.AveragingLength = 256 * 4;
AGCConfig.MaxPowerGain = 400;

txRF = TRFSimulator(StartTime=0.2, ...
    SampleRate = SampleRate, ...
    CarrierFrequency=CarrierFrequency, ...
    IqImbalanceConfig=IqImbalanceConfig, ...
    PhaseNoiseConfig=PhaseNoiseConfig, ...
    MasterClockRate = MasterClockRate, ...
    MemoryLessNonlinearityConfig=MemoryLessNonlinearityConfig);
rayChannel = Rayleigh(CarrierFrequency=CarrierFrequency, ...
    SampleRate=SampleRate, PathDelays=0, ...
    AveragePathGains=0, MaximumDopplerShift=0);

ricChannel = Rician(CarrierFrequency=CarrierFrequency, ...
    SampleRate=SampleRate, PathDelays=0, ...
    AveragePathGains=0, MaximumDopplerShift=0);

rxRF = RRFSimulator(StartTime=0, TimeDuration=5, SampleRate=SampleRate, ...
    NumReceiveAntennas=1, CarrierFrequency=30e3, Bandwidth=20e3, ...
    MasterClockRate=MasterClockRate, ...
    MemoryLessNonlinearityConfig=MemoryLessNonlinearityConfig, ...
    ThermalNoiseConfig=ThermalNoiseConfig, ...
    PhaseNoiseConfig=PhaseNoiseConfig, ...
    AGCConfig=AGCConfig, ...
    IqImbalanceConfig=IqImbalanceConfig);

source = Audio(SampleRate = SampleRate, TimeDuration = TimeDuration);

x = source();

%% Test FM
ModulatorConfig.FrequencyDeviation = 75e3;
ModulatorConfig.InitPhase = pi / 4;
baseBandSignal = FM(ModulatorConfig = ModulatorConfig, ...
    NumTransmitAntennnas = NumTransmitAntennnas, ...
    SampleRate=SampleRate);

x1= baseBandSignal(x);

% demod FM and verify
upConv = dsp.DigitalUpConverter(...
    'InterpolationFactor', 5,...
    'SampleRate', x1.SampleRate,...
    'Bandwidth', x1.BandWidth,...
    'StopbandAttenuation', 55,...
    'PassbandRipple',0.2,...
    'CarrierFrequency',40e3);

dwnConv = dsp.DigitalDownConverter(...
    'DecimationFactor',5,...
    'SampleRate', x1.SampleRate*5,...
    'Bandwidth', x1.BandWidth,...
    'StopbandAttenuation', 55,...
    'PassbandRipple',0.2,...
    'CarrierFrequency',40e3);

a = x1.data;
b = upConv(a);
scope1 = spectrumAnalyzer(SampleRate=x1.SampleRate*5,AveragingMethod="exponential",RBWSource="auto",SpectrumUnits="dBW");
scope1(b);

c = dwnConv(b);
scope2 = spectrumAnalyzer(SampleRate=x1.SampleRate,AveragingMethod="exponential",RBWSource="auto",SpectrumUnits="dBW");
scope2(c);

fmDeMod = comm.FMDemodulator("SampleRate", x1.SampleRate, "FrequencyDeviation", ModulatorConfig.FrequencyDeviation);

d = lowpass(c, 60e3, x1.SampleRate, ...
    ImpulseResponse = "fir", ...
    Steepness = 0.99999, StopbandAttenuation=200);
e = fmDeMod(d);

