classdef MIMO < BaseChannel

    methods

        function channel = getChannel(obj)

            if strcmp(obj.channelConfig.fadingDistribution, 'Rayleigh')
                channel = comm.MIMOChannel( ...
                    SampleRate = obj.channelConfig.sampleRate, ...
                    PathDelays = obj.channelConfig.pathDelays, ...
                    AveragePathGains = obj.channelConfig.averagePathGains, ...
                    NormalizePathGains = obj.channelConfig.normalizePathGains, ...
                    FadingDistribution = 'Rayleigh', ...
                    MaximumDopplerShift = obj.channelConfig.maximumDopplerShift, ...
                    DopplerSpectrum = obj.channelConfig.dopplerSpectrum, ...
                    SpatialCorrelationSpecification = 'None', ...
                    NumTransmitAntennas = obj.channelConfig.NumTransmitAntennas, ...
                    NumReceiveAntennas = obj.channelConfig.NumReceiveAntennas);
            else
                channel = comm.MIMOChannel( ...
                    SampleRate = obj.channelConfig.sampleRate, ...
                    PathDelays = obj.channelConfig.pathDelays, ...
                    AveragePathGains = obj.channelConfig.averagePathGains, ...
                    NormalizePathGains = obj.channelConfig.normalizePathGains, ...
                    FadingDistribution = 'Rayleigh', ...
                    KFactor = obj.channelConfig.KFactor, ...
                    DirectPathDopplerShift = obj.channelConfig.directPathDopplerShift, ...
                    DirectPathInitialPhase = obj.channelConfig.directPathInitialPhase, ...
                    MaximumDopplerShift = obj.channelConfig.maximumDopplerShift, ...
                    DopplerSpectrum = obj.channelConfig.dopplerSpectrum, ...
                    SpatialCorrelationSpecification = 'None', ...
                    NumTransmitAntennas = obj.channelConfig.NumTransmitAntennas, ...
                    NumReceiveAntennas = obj.channelConfig.NumReceiveAntennas);
            end

        end

    end

end
