classdef Rician < BaseChannel

    methods

        function channel = getChannel(obj)

            channel = comm.RicianChannel( ...
                SampleRate = obj.channelConfig.sampleRate, ...
                PathDelays = obj.channelConfig.pathDelays, ...
                AveragePathGains = obj.channelConfig.averagePathGains, ...
                NormalizePathGains = obj.channelConfig.normalizePathGains, ...
                KFactor = obj.channelConfig.KFactor, ...
                DirectPathDopplerShift = obj.channelConfig.directPathDopplerShift, ...
                DirectPathInitialPhase = obj.channelConfig.directPathInitialPhase, ...
                MaximumDopplerShift = obj.channelConfig.maximumDopplerShift, ...
                DopplerSpectrum = obj.channelConfig.dopplerSpectrum);

        end

    end

end
