function results = run_csrd_downstream_docs_readiness(varargin)
%RUN_CSRD_DOWNSTREAM_DOCS_READINESS Validate Phase 7 downstream docs.
% Inputs / 输入: see signature arguments and local validation.
% 输出 / Outputs: see signature return values and contract fields.
% 中文说明：提供 CSRD 生产链路中的 run_csrd_downstream_docs_readiness 实现。
%
%   RESULTS = run_csrd_downstream_docs_readiness() checks the release notes,
%   annotation v2 schema docs, downstream example docs, and executable
%   downstream example without running a simulation.

p = inputParser;
addParameter(p, 'Verbose', true, @islogical);
parse(p, varargin{:});

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
docs = localRequiredDocs(projectRoot);
docChecks = localValidateDocs(docs);

examplePath = fullfile(projectRoot, 'examples', ...
    'read_annotation_v2_downstream.m');
assert(exist(examplePath, 'file') == 2, ...
    'CSRD:ReleaseDocs:MissingExample', ...
    'Downstream executable example is missing: %s', examplePath);
exampleIssues = checkcode(examplePath, '-id');
assert(isempty(exampleIssues), ...
    'CSRD:ReleaseDocs:ExampleCodeAnalyzer', ...
    'Downstream executable example has code analyzer issues.');

results = struct( ...
    'Success', true, ...
    'ProjectRoot', projectRoot, ...
    'Schema', 'csrd.phase7.downstream-docs-readiness.v1', ...
    'Documentation', docChecks, ...
    'ExecutableExamplePath', examplePath, ...
    'ExampleAnalyzerIssueCount', numel(exampleIssues));

if p.Results.Verbose
    fprintf('=== CSRD downstream docs readiness PASSED ===\n');
    fprintf('Documents checked: %d\n', numel(docChecks));
end
end


function docs = localRequiredDocs(projectRoot)
    % localRequiredDocs - Production declaration in CSRD.
    % 中文说明：localRequiredDocs 在 CSRD 生产链路中执行对应处理。
    % Inputs / 输入: see signature arguments and local validation.
    % 输出 / Outputs: see signature return values and contract fields.
docs = {
    fullfile(projectRoot, 'docs', 'annotation-v2-schema.md'), ...
        {'Truth.Design', 'Truth.Execution', 'Truth.Measured', ...
         'ReceiverView', 'MeasurementSemantics', ...
         'Legacy v1 top-level fields are forbidden'};
    fullfile(projectRoot, 'docs', 'examples', ...
        'annotation-v2-downstream.md'), ...
        {'readAnnotationV2', 'convert_csrd_to_coco', ...
         'RequireSources', 'receiver-frequency canvas', ...
         'Truth.Measured.SourcePlane.OccupiedBandwidthHz'};
    fullfile(projectRoot, 'docs', 'release', ...
        'RELEASE_NOTES_v0.5.0.md'), ...
        {'Phase 0-6 are', 'No annotation v1 compatibility', ...
         'ExecutionVsMeasuredBwAbsRelDiffP95', ...
         'run_csrd_release_ci_readiness', ...
         'no 1000-scenario MC'};
    fullfile(projectRoot, 'examples', 'read_annotation_v2_downstream.m'), ...
        {'readAnnotationV2', 'convert_csrd_to_coco', ...
         'RequireRuntimeHeader', 'CocoCoordinateSystem'}};
end


function checks = localValidateDocs(docs)
    % localValidateDocs - Production declaration in CSRD.
    % 中文说明：localValidateDocs 在 CSRD 生产链路中执行对应处理。
    % Inputs / 输入: see signature arguments and local validation.
    % 输出 / Outputs: see signature return values and contract fields.
checks = repmat( ...
    struct('Path', '', 'Needles', {{}}, 'Matched', false), ...
    size(docs, 1), 1);
for k = 1:size(docs, 1)
    path = docs{k, 1};
    needles = docs{k, 2};
    assert(exist(path, 'file') == 2, ...
        'CSRD:ReleaseDocs:MissingDocument', ...
        'Required downstream document is missing: %s', path);
    text = fileread(path);
    for j = 1:numel(needles)
        assert(contains(text, needles{j}), ...
            'CSRD:ReleaseDocs:DocumentContentMismatch', ...
            'Required downstream document %s does not contain "%s".', ...
            path, needles{j});
    end
    checks(k).Path = path;
    checks(k).Needles = needles;
    checks(k).Matched = true;
end
end
