function profile = Broadcast_FM_VHF()
%BROADCAST_FM_VHF v0 band profile: VHF FM broadcast (87.5-108 MHz).
% Inputs / 输入: see signature arguments and local validation.
% 输出 / Outputs: see signature return values and contract fields.
% 中文说明：提供 CSRD 生产链路中的 Broadcast_FM_VHF 实现。
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis A (row 1).
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.A.

    profile = struct( ...
        'FrequencyRangeHz',              [87.5e6 108e6], ...
        'RecommendedBandwidthsHz',       {{200e3}}, ...
        'RecommendedModulationFamilies', {{'FM','PM','DSBSCAM'}}, ...
        'TemporalPattern',               'Continuous', ...
        'BurstOnTimeRangeMs',            [], ...
        'BurstOffTimeRangeMs',           [], ...
        'RecommendedTxAntennas',         [1 1], ...
        'TypicalNoiseFigureDb',          8, ...
        'RecommendedRxProfiles',         {{'LabAnalyzer_160MHz','PortableMonitor_40MHz'}});
end
