function profile = Broadcast_AM_MW()
%BROADCAST_AM_MW v0 band profile: medium-wave AM broadcast (531-1602 kHz).
% Inputs: see signature arguments and local validation.
% Outputs: see signature return values and contract fields.
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis A (row 2).
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.A.

    profile = struct( ...
        'FrequencyRangeHz',              [531e3 1602e3], ...
        'RecommendedBandwidthsHz',       {{9e3}}, ...
        'RecommendedModulationFamilies', {{'DSBAM','SSBAM'}}, ...
        'TemporalPattern',               'Continuous', ...
        'BurstOnTimeRangeMs',            [], ...
        'BurstOffTimeRangeMs',           [], ...
        'RecommendedTxAntennas',         [1 1], ...
        'TypicalNoiseFigureDb',          10, ...
        'RecommendedRxProfiles',         {{'LabAnalyzer_160MHz'}});
end
