function profile = NR_n78()
%NR_N78 v0 band profile: 5G NR band n78 (3300-3600 MHz).
% Inputs / 输入: see signature arguments and local validation.
% 输出 / Outputs: see signature return values and contract fields.
% 中文说明：提供 CSRD 生产链路中的 NR_n78 实现。
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis A (row 6).
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.A.

    profile = struct( ...
        'FrequencyRangeHz',              [3300e6 3600e6], ...
        'RecommendedBandwidthsHz',       {{20e6, 40e6, 80e6, 100e6}}, ...
        'RecommendedModulationFamilies', {{'OFDM'}}, ...
        'TemporalPattern',               'Continuous', ...
        'BurstOnTimeRangeMs',            [], ...
        'BurstOffTimeRangeMs',           [], ...
        'RecommendedTxAntennas',         [1 4], ...
        'TypicalNoiseFigureDb',          6, ...
        'RecommendedRxProfiles',         {{'LabAnalyzer_160MHz','DenseArrayStation_200MHz'}});
end
