function profile = DenseArrayStation_200MHz()
%DENSEARRAYSTATION_200MHZ v0 receiver profile: fixed dense-array station, 200 MHz Fs.
% Inputs: see signature arguments and local validation.
% Outputs: see signature return values and contract fields.
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis B (row 3).
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.B.
%
% Hard constraint (§5.bis B): SampleRate == ObservableBandwidth.

    profile = struct( ...
        'SampleRateChoicesHz',     {{80e6, 160e6, 200e6}}, ...
        'ObservableBandwidthHz',   [], ...
        'NumAntennasRange',        [4 16], ...
        'NoiseFigureRangeDb',      [4 6], ...
        'SensitivityDbm',          -115, ...
        'CarrierFrequencyRangeHz', [600e6 12e9]);
end
