classdef OQPSK < APSK

    methods

        function modulatorHandle = genModulator(obj)
            obj.filterCoeffs = obj.genFilterCoeffs;
            obj.ostbc = obj.genOSTBC;
            modulatorHandle = BaseOQPSK( ...
                PhaseOffset = obj.ModulatorConfig.phaseOffset, ...
                SymbolMapping = obj.ModulatorConfig.symbolMapping, ...
                PulseShape = 'Root raised cosine', ...
                RolloffFactor = obj.ModulatorConfig.beta, ...
                FilterSpanInSymbols = obj.ModulatorConfig.span, ...
                SamplesPerSymbol = obj.SamplePerSymbol, ...
                NumTransmitAntennas = obj.NumTransmitAntennas, ...
                ostbc = obj.ostbc);

            obj.IsDigital = true;

        end

    end

end
