function summary = read_annotation_downstream(annotationPath, cocoOutputPath)
%READ_ANNOTATION_DOWNSTREAM Downstream annotation reader example.
%
%   SUMMARY = read_annotation_downstream(ANNOTATIONPATH) validates a CSRD
%   annotation JSON file and returns source/frame counts.
%
%   SUMMARY = read_annotation_downstream(ANNOTATIONPATH, COCOOUTPUTPATH)
%   also writes the minimal receiver-frequency COCO export.

if nargin < 1 || isempty(annotationPath)
    error('CSRD:Example:MissingAnnotationPath', ...
        'annotationPath is required.');
end
if nargin < 2
    cocoOutputPath = '';
end

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'tools'));

reader = csrd.pipeline.annotation.readAnnotation(annotationPath, ...
    'RequireSources', true, ...
    'RequireRuntimeHeader', true);
coco = convert_csrd_to_coco(annotationPath, cocoOutputPath);

summary = struct( ...
    'Schema', reader.Summary.Schema, ...
    'NumFrames', reader.Summary.NumFrames, ...
    'NumSources', reader.Summary.NumSources, ...
    'NumReceivers', reader.Summary.NumReceivers, ...
    'ReceiverIDs', {reader.Summary.ReceiverIDs}, ...
    'NumCocoImages', numel(coco.images), ...
    'NumCocoAnnotations', numel(coco.annotations), ...
    'NumSkippedSources', coco.csrd_export.num_skipped_sources, ...
    'CocoCoordinateSystem', coco.info.coordinate_system);

fprintf('CSRD annotation: %d frames, %d sources, %d COCO annotations\n', ...
    summary.NumFrames, summary.NumSources, summary.NumCocoAnnotations);
end
