
fs = 150e3;                  % Sample rate

% noise

% channel
rayleigh_channel = comm.RayleighChannel( ...
      'SampleRate', fs, ...
      'PathDelays', [0 1.8 3.4] / fs, ...
      'AveragePathGains', obj.AveragePathGains, ...
      'MaximumDopplerShift', obj.MaximumDopplerShift);
rician_channel = comm.RicianChannel(...
        'SampleRate', fs, ...
        'PathDelays', [0 1.8 3.4] / fs, ...
        'AveragePathGains', [0 -2 -10], ...
        'KFactor', 4, ...
        'MaximumDopplerShift', 4);

% 
frequency_shifter = comm.PhaseFrequencyOffset('SampleRate', fs);