classdef GMSK < FSK

    methods

        function modulatorHandle = genModulator(obj)
            modulatorHandle = comm.GMSKModulator( ...
                BitInput = true, ...
                BandwidthTimeProduct = obj.ModulatorConfig.BandwidthTimeProduct, ...
                PulseLength = obj.ModulatorConfig.PulseLength, ...
                SymbolPrehistory = obj.ModulatorConfig.SymbolPrehistory, ...
                InitialPhaseOffset = obj.ModulatorConfig.InitialPhaseOffset, ...
                SamplesPerSymbol = obj.SamplePerSymbol);
            obj.NumTransmitAntennnas = 1;
            obj.IsDigital = true;
        end

    end

end
