function recipe = baseline_recipe_v0()
    %BASELINE_RECIPE_V0 Deterministic 200-scenario recipe for Phase 0 baseline.
    %
    %   Returns a struct with two fields:
    %     .NumScenarios      total scenario count (== 200 by definition)
    %     .Cohorts           struct array describing each cohort
    %
    %   Cohort fields:
    %     .Name              short identifier (used in baseline JSON)
    %     .Count             scenario count for this cohort
    %     .ScenarioIdRange   [first, last] scenario id covered
    %     .BandLabel         human-readable band tag
    %     .MapTypes          cell array passed to Scenario.PhysicalEnvironment.Map.Types
    %     .MapRatio          weights matching MapTypes
    %     .PatternTypes      cell array of CommunicationBehavior temporal patterns
    %     .PatternDistribution
    %     .TxRange           [min, max] number of transmitters
    %     .RxRange           [min, max] number of receivers
    %     .NumFramesPerScenario
    %     .ObservationDuration
    %     .CohortMaxSpeedMps Phase 4 (audit §3.8.A/.C) cohort-driven
    %                        per-axis velocity cap. When > 0, projected
    %                        to `Entities.Transmitters.Mobility.MaxSpeedMps`
    %                        in localCohortToRunnerCfg so PhysicalEnvironmentSimulator
    %                        / getMaxSpeedForEntityType bumps the
    %                        sampled velocity envelope (used by the
    %                        HighSpeed_Aero_Doppler cohort to provide
    %                        v >= 100 m/s samples for the C2 Doppler
    %                        regression).
    %     .ChannelPreference Phase 4 (audit §3.8.B) explicit channel
    %                        model hint (e.g. 'AWGN' / 'Rayleigh') applied
    %                        through the scenario map ChannelModel. Empty
    %                        string = cohort accepts factory defaults.
    %
    %   This file is a helper, not a regression test in its own right.
    %   run_all_tests' regression scanner globs `test_*.m`, so naming
    %   it without the `test_` prefix keeps it out of the auto-run set.
    %   It is consumed only by `test_baseline_sweep_200.m` and by
    %   Phase 1+ regression suites.
    %
    %   Source of truth: phase-0-baseline.md §3.4.

    cohorts = struct( ...
        'Name', '', 'Count', 0, 'ScenarioIdRange', [0, 0], ...
        'BandLabel', '', 'MapTypes', {{}}, 'MapRatio', [], ...
        'PatternTypes', {{}}, 'PatternDistribution', [], ...
        'TxRange', [0, 0], 'RxRange', [0, 0], ...
        'NumFramesPerScenario', 0, 'ObservationDuration', 0, ...
        'CohortMaxSpeedMps', 0, 'ChannelPreference', '');

    % Phase 3 unblocked (audit §3.1.ter / §3.6.D / §10 Q2 = B):
    %   Phase 2 pinned RxRange = [1, 1] for every cohort because the
    %   BlueprintFeasibilityValidator #13 ReceiverViewProjectionPresent
    %   check rejected any multi-Rx blueprint that lacked a per-receiver
    %   ReceiverViews projection on each Emitter. Phase 3 lands that
    %   projection in CommunicationBehaviorSimulator (S2) +
    %   BlueprintFeasibilityValidator (#3 / #13 schema upgrade, S1) +
    %   downstream construction-layer consumers (S3 / S4), so the
    %   validator now accepts true multi-Rx blueprints.
    %
    %   (cohorts 1 / 2 / 3, 120 scenarios total) are restored to their
    %   design-time RxRange = [1, 2] so Phase 3 actually exercises the
    %   ReceiverViews projection in baseline. Cohorts 4 / 5 / 6 / 7
    %   (2.4 GHz AWGN, 2.4 GHz AWGN, FM, AM -- 80 scenarios) stay at
    %   [1, 1] because FM / AM broadcast cohorts are intentionally
    %   single-Rx and the 2.4 GHz cohorts stress OFDM/frequency planning
    %   without adding Rx fan-out cost.
    %   Expected multi-Rx scenario share: ≈ 60 / 200 = 30 % (same as
    %   the §10 Q2 (B) target).
    %
    %   DO NOT widen RxRange on cohorts 4-7 without also reviewing the
    %   C8 / C9 baseline acceptance and wallclock thresholds in
    %   phase-3-construction.md §7.
    cohorts(1) = mkCohort( ...
        'Sub3GHz_AWGN_PSKQAM',          40, ...
        'Sub-3GHz', {'Statistical'}, [1.0], ...
        {'Continuous'}, [1.0], [2, 3], [1, 2], 1, 0.005, ...
        'ChannelPreference', 'AWGN');

    cohorts(2) = mkCohort( ...
        'Sub3GHz_RayleighMIMO_OFDM',    40, ...
        'Sub-3GHz', {'Statistical'}, [1.0], ...
        {'Continuous'}, [1.0], [2, 4], [1, 2], 1, 0.005, ...
        'ChannelPreference', 'Rayleigh');

    cohorts(3) = mkCohort( ...
        'Sub3GHz_RicianMIMO_Mixed',     40, ...
        'Sub-3GHz', {'Statistical'}, [1.0], ...
        {'Continuous', 'Burst'}, [0.7, 0.3], [2, 3], [1, 2], 1, 0.005, ...
        'ChannelPreference', 'Rician');

    cohorts(4) = mkCohort( ...
        '2p4GHz_AWGN_OFDM_A',           40, ...
        '2.4GHz', {'Statistical'}, [1.0], ...
        {'Continuous'}, [1.0], [1, 2], [1, 1], 1, 0.005, ...
        'ChannelPreference', 'AWGN');

    cohorts(5) = mkCohort( ...
        '2p4GHz_AWGN_OFDM_B',           20, ...
        '2.4GHz', {'Statistical'}, [1.0], ...
        {'Continuous'}, [1.0], [1, 2], [1, 1], 1, 0.005, ...
        'ChannelPreference', 'AWGN');

    cohorts(6) = mkCohort( ...
        'FMBroadcast_AWGN',             10, ...
        'FM', {'Statistical'}, [1.0], ...
        {'Continuous'}, [1.0], [1, 1], [1, 1], 1, 0.005, ...
        'ChannelPreference', 'AWGN');

    cohorts(7) = mkCohort( ...
        'AMBroadcast_AWGN',             10, ...
        'AM', {'Statistical'}, [1.0], ...
        {'Continuous'}, [1.0], [1, 1], [1, 1], 1, 0.005, ...
        'ChannelPreference', 'AWGN');

    % Phase 4 (audit §3.8 / §6 C2): high-speed aero cohort feeding
    % the C8 baseline metric `MaxAbsDopplerShiftHz` (AWGN-only path
    % so wallclock stays well under the §7 +15 % budget; 200 m/s per
    % §3.8.A which is the cohort-sampled ceiling, not a per-axis
    % component cap). The accompanying deterministic regression
    % `tests/regression/test_doppler_high_speed.m` (S10) provides
    % the f_d ≈ v_radial · f_c / c < 5 % accuracy gate; this cohort
    % only needs to provide samples where v >= 100 m/s actually
    % occurs in the baseline so MeasuredTruth.SourcePlane carries
    % a non-zero Doppler shift across the sweep.
    cohorts(8) = mkCohort( ...
        'HighSpeed_Aero_Doppler',       10, ...
        'Sub-3GHz', {'Statistical'}, [1.0], ...
        {'Continuous'}, [1.0], [1, 2], [1, 1], 1, 0.005, ...
        'CohortMaxSpeedMps', 200, 'ChannelPreference', 'AWGN');

    % Tag scenario id ranges deterministically.
    nextStart = 1;
    for k = 1:numel(cohorts)
        cohorts(k).ScenarioIdRange = ...
            [nextStart, nextStart + cohorts(k).Count - 1];
        nextStart = nextStart + cohorts(k).Count;
    end

    total = sum([cohorts.Count]);
    assert(total == 210, ...
        '_baseline_recipe_v0 must total 210 scenarios; got %d', total);

    recipe = struct( ...
        'SchemaVersion', 'baseline-recipe-v0', ...
        'NumScenarios', total, ...
        'Cohorts', cohorts);
end


function c = mkCohort(name, count, band, mapTypes, mapRatio, ...
        patternTypes, patternDist, txRange, rxRange, ...
        numFrames, observationDuration, varargin)
    % Phase 4 (audit §3.8.A/.B/.C): added two optional Name-Value pairs
    % so the HighSpeed_Aero_Doppler cohort can lift the per-entity-type
    % velocity ceiling and pin the channel preference. Earlier cohorts
    % omit these pairs and inherit the factory defaults
    % (CohortMaxSpeedMps=0 → no override, ChannelPreference='' → no hint).
    p = inputParser;
    p.FunctionName = 'mkCohort';
    p.CaseSensitive = true;
    p.KeepUnmatched = false;
    addParameter(p, 'CohortMaxSpeedMps', 0, ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
    addParameter(p, 'ChannelPreference', '', ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));
    parse(p, varargin{:});

    c = struct( ...
        'Name', name, ...
        'Count', count, ...
        'ScenarioIdRange', [0, 0], ...
        'BandLabel', band, ...
        'MapTypes', {mapTypes}, ...
        'MapRatio', mapRatio, ...
        'PatternTypes', {patternTypes}, ...
        'PatternDistribution', patternDist, ...
        'TxRange', txRange, ...
        'RxRange', rxRange, ...
        'NumFramesPerScenario', numFrames, ...
        'ObservationDuration', observationDuration, ...
        'CohortMaxSpeedMps', double(p.Results.CohortMaxSpeedMps), ...
        'ChannelPreference', char(p.Results.ChannelPreference));
end
