classdef Phase0FakeEngine < matlab.System
    %PHASE0FAKEENGINE Minimal engine stand-in for Phase 0 startup tests.
    %
    %   This class plugs into csrd.SimulationRunner via
    %   RunnerConfig.Engine.Handle = 'Phase0FakeEngine'. It returns ONE
    %   frame whose annotation is deliberately poisoned with values that
    %   sanitizeForJson must coerce:
    %       NaN, +Inf, -Inf, complex number, datetime, function_handle.
    %
    %   It does NOT exercise any real factory, modulator, or channel.
    %   Phase 1+ regression tests are responsible for end-to-end
    %   correctness; this fake exists purely so we can verify the four
    %   Phase 0 hooks in SimulationRunner.setupImpl/saveScenarioData
    %   without dragging in the entire simulation chain.
    %
    %   Phase 4 (audit §17.6 / S13): the fabricated SignalSources entry
    %   has been migrated from the v1 top-level layout (Realized /
    %   Planned / Spatial) to the v2 Truth.{Design, Execution, Measured}
    %   hierarchy + the v2 top-level required keys (TxID / SegmentId /
    %   BurstId / Truth / RFImpairments / ReceiverView). The fixture
    %   keeps a finite SourcePlane.OccupiedBandwidthHz so the Phase 4
    %   `validateMeasurementCompleteness` write-back hook accepts it,
    %   and continues to inject NaN / Inf / complex / function_handle
    %   poison values in *non-required* slots so sanitizeForJson still
    %   has a workout.

    properties
        FactoryConfigs struct
        RuntimePlan struct
    end

    properties (SetAccess = private, GetAccess = public)
        % LastGlobalLayout - Phase 3 (audit §3.5 / §17.5 P3-7) parity field.
        % csrd.SimulationRunner reads `engine.LastGlobalLayout` directly
        % (no ismethod / try-catch ladder) and feeds it to
        % csrd.core.ChangShuo.extractProvenanceFromGlobalLayout. Phase0FakeEngine
        % does not run the real ScenarioFactory so it cannot synthesize a
        % real BlueprintHash; we expose an empty struct so the helper
        % returns the canonical three-key default (BlueprintHash='',
        % BlueprintResamples=0, ValidatorVersion=''). This keeps the
        % Phase 0 startup-hook regression compatible with the Phase 3
        % provenance dataflow without weakening the property's read-only
        % contract.
        LastGlobalLayout = struct();
    end

    methods (Access = protected)
        function setupImpl(~)
        end

        function [scenarioData, scenarioAnnotation] = stepImpl(~, ~)
            % Fabricate a one-frame, one-rx, one-source response.
            frameSamples = complex(zeros(8, 1), zeros(8, 1));
            frameSamples(1:4) = 1 + 1i;

            rxPayload = struct( ...
                'Signal',     frameSamples, ...
                'SampleRate', 1e6);
            scenarioData = {{rxPayload}};

            % Phase 4 v2 schema: Truth.{Design, Execution, Measured}
            % must each be present, and SignalSources must carry TxID /
            % SegmentId / BurstId / Truth / RFImpairments /
            % ReceiverView. validateMeasurementCompleteness additionally
            % requires a finite OccupiedBandwidthHz on at least one of
            % SourcePlane / FramePlane (audit §3.7.D test (b)/(c)).
            % Poison values (NaN / Inf / complex / function_handle) are
            % injected in *optional* slots so sanitizeForJson still has
            % a workout without breaking the v2 fail-fast contract.
            designTruth = struct( ...
                'PlannedBandwidthHz',       100e3, ...
                'PlannedCenterFrequencyHz', 1e9, ...
                'BadDesignNan',             NaN);
            executionTruth = struct( ...
                'ModulatedBandwidthHz',     99.5e3, ...
                'AnalyticalBandwidthHz',    100e3, ...
                'CenterFrequencyOffsetHz', 0, ...
                'AppliedSNRdB',            20, ...
                'DopplerShiftHz',          0, ...
                'RadialVelocityMps',       0, ...
                'BadExecInf',              Inf, ...
                'BadExecNegInf',          -Inf);
            sourcePlane = struct( ...
                'OccupiedBandwidthHz',  99.5e3, ...
                'CenterFrequencyHz',    1e9, ...
                'SNRdB',                20, ...
                'TimeOccupancy',        1.0, ...
                'FrequencyOccupancy',   0.5, ...
                'MeasurementSemantics', 'Phase4FakeIsolated');
            framePlane = struct( ...
                'OccupiedBandwidthHz',  120e3, ...
                'CenterFrequencyHz',    1e9, ...
                'TimeOccupancy',        1.0, ...
                'FrequencyOccupancy',   0.6, ...
                'MeasurementSemantics', 'Phase4FakeFrame');
            measuredTruth = struct( ...
                'SourcePlane', sourcePlane, ...
                'FramePlane',  framePlane);
            truth = struct( ...
                'Design',    designTruth, ...
                'Execution', executionTruth, ...
                'Measured',  measuredTruth);

            receiverView = struct( ...
                'ReceiverId',                'Rx-fake-001', ...
                'ProjectedCenterOffsetHz',   0, ...
                'ProjectedLowerEdgeHz',     -50e3, ...
                'ProjectedUpperEdgeHz',      50e3, ...
                'IsVisible',                 true, ...
                'VisibilityReason',          'Phase4FakeVisible');

            rfImpairments = struct( ...
                'PhaseNoiseDbcHz',  -110, ...
                'IqImbalanceDb',    0.5, ...
                'BadImpairment',    1 + 2i);

            poisonedSource = struct( ...
                'TxID',          'tx-fake-001', ...
                'SegmentId',     1, ...
                'BurstId',       1, ...
                'Truth',         truth, ...
                'RFImpairments', rfImpairments, ...
                'ReceiverView',  receiverView, ...
                'BadComplex',    1 + 2i, ...
                'BadHandle',     @(x) x.^2);
            rxAnnotation = struct( ...
                'Status', 'OK', ...
                'NumSignalComponents', 1, ...
                'SignalSources', poisonedSource);
            scenarioAnnotation = {{rxAnnotation}};
        end

        function cleanupImpl(~)
        end
    end

    methods
        function obj = Phase0FakeEngine(varargin)
            setProperties(obj, nargin, varargin{:});
        end

        function cleanup(obj)
            release(obj);
        end
    end
end
