function test_phase6_coco_converter_fixture()
%TEST_PHASE6_COCO_CONVERTER_FIXTURE File-level COCO v2 export regression.
%
% This regression uses a synthetic annotation v2 fixture. It does not run
% the simulator and does not depend on generated artifacts.

here = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(here));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'tools'));

payload = localFixturePayload();
outDir = tempname;
cleanup = onCleanup(@() localRemoveDir(outDir));
outPath = fullfile(outDir, 'coco', 'fixture.json');

coco = convert_csrd_to_coco(payload, outPath, 'ImageWidth', 512);

assert(isfile(outPath), 'Phase 6 COCO fixture JSON was not written.');
assert(strcmp(coco.info.version, 'csrd-coco-v2-minimal'), ...
    'Unexpected COCO converter version.');
assert(numel(coco.images) == 2, 'Expected one image per receiver frame.');
assert(isscalar(coco.annotations), ...
    'Expected one visible source annotation.');
assert(coco.csrd_export.num_skipped_sources == 1, ...
    'Expected one invisible source to be skipped explicitly.');
assert(strcmp(coco.csrd_export.field_sources.category, ...
    'Truth.Design.ModulationFamily'), ...
    'COCO export must preserve source-field provenance.');

decoded = jsondecode(fileread(outPath));
assert(decoded.csrd_export.num_annotations == 1, ...
    'Written JSON annotation count drifted from returned struct.');
assert(decoded.annotations.bbox(3) > 0, ...
    'Written JSON bbox width must be positive.');

delete(cleanup);
end


function payload = localFixturePayload()
visible = localSource('Tx1', true, 'InBand', 0);
invisible = localSource('Tx2', false, 'OutOfBand', 2e6);

frame1 = localFrame(1, 'Rx1', visible);
frame2 = localFrame(2, 'Rx1', invisible);

payload = struct( ...
    'Frames', {{ {frame1, frame2} }}, ...
    'Header', struct( ...
        'Runtime', struct( ...
            'BlueprintHash', 'phase6-coco-fixture', ...
            'ValidatorVersion', 'phase6-test')));
end


function frame = localFrame(frameId, receiverId, source)
frame = struct( ...
    'FrameId', frameId, ...
    'ReceiverID', receiverId, ...
    'ReceiverType', 'monitor', ...
    'SampleRate', 10e6, ...
    'ObservableRange', [-5e6 5e6], ...
    'Status', 'Success', ...
    'SignalSources', source);
end


function source = localSource(txId, isVisible, reason, centerOffsetHz)
sourcePlane = struct( ...
    'OccupiedBandwidthHz', 1e6, ...
    'CenterFrequencyHz', 0, ...
    'SNRdB', 18, ...
    'TimeOccupancy', 1, ...
    'FrequencyOccupancy', 0.1, ...
    'MeasurementSemantics', 'receiver_view_isolated');

framePlane = struct( ...
    'OccupiedBandwidthHz', 1.1e6, ...
    'CenterFrequencyHz', centerOffsetHz, ...
    'TimeOccupancy', 1, ...
    'FrequencyOccupancy', 0.11, ...
    'MeasurementSemantics', 'post_rx_combined_pre_rfchain');

geometry = struct( ...
    'TxPositionM', [0 0 10], ...
    'TxVelocityMps', [0 0 0], ...
    'RxPositionM', [100 0 10], ...
    'RxVelocityMps', [0 0 0], ...
    'LinkDistanceM', 100);

design = struct( ...
    'PlannedCenterFrequencyHz', 2.4e9, ...
    'PlannedBandwidthHz', 1e6, ...
    'PlannedSampleRate', 5e6, ...
    'ModulationFamily', 'QPSK', ...
    'ModulationOrder', 4, ...
    'PayloadLengthBits', 1024, ...
    'NumTransmitAntennas', 1);

execution = struct( ...
    'ModulatedBandwidthHz', 1e6, ...
    'CenterFrequencyOffsetHz', centerOffsetHz, ...
    'SampleRate', 5e6, ...
    'ChannelModel', 'AWGN', ...
    'PathLossDB', 80, ...
    'AnalyticalSNRdB', 18, ...
    'AppliedSNRdB', 18, ...
    'DopplerShiftHz', 0, ...
    'RadialVelocityMps', 0, ...
    'GeometrySnapshot', geometry);

source = struct( ...
    'TxID', txId, ...
    'SegmentId', 1, ...
    'BurstId', [txId '-Burst1'], ...
    'Truth', struct( ...
        'Design', design, ...
        'Execution', execution, ...
        'Measured', struct( ...
            'SourcePlane', sourcePlane, ...
            'FramePlane', framePlane)), ...
    'RFImpairments', struct(), ...
    'ReceiverView', struct( ...
        'ReceiverId', 'Rx1', ...
        'ProjectedCenterOffsetHz', centerOffsetHz, ...
        'ProjectedLowerEdgeHz', centerOffsetHz - 5e5, ...
        'ProjectedUpperEdgeHz', centerOffsetHz + 5e5, ...
        'IsVisible', isVisible, ...
        'VisibilityReason', reason));
end


function localRemoveDir(path)
if exist(path, 'dir') == 7
    rmdir(path, 's');
end
end
