function test_phase14_production_bilingual_comment_audit()
%TEST_PHASE14_PRODUCTION_BILINGUAL_COMMENT_AUDIT Gate declaration-level comments.
% 中文说明：验证生产 MATLAB 文件已完成函数/方法级中英文注释补救。

fprintf('=== Phase 14 production bilingual comment audit ===\n');
projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(projectRoot);

summary = csrd.support.docs.auditProductionComments( ...
    'ProjectRoot', projectRoot, 'ApplyFixes', false);

assert(summary.FilesAudited >= 230, ...
    'Production comment audit covered too few MATLAB files.');
assert(summary.DeclarationsAudited >= 900, ...
    'Production declaration audit covered too few class/function declarations.');
assert(summary.MissingBilingualHeader == 0, ...
    'Production files missing bilingual headers: %d.', ...
    summary.MissingBilingualHeader);
assert(summary.MissingDeclarationBilingualComment == 0, ...
    'Production declarations missing bilingual comments: %d.', ...
    summary.MissingDeclarationBilingualComment);
assert(summary.MissingDeclarationInputOutputComment == 0, ...
    'Production functions missing bilingual I/O comments: %d.', ...
    summary.MissingDeclarationInputOutputComment);
assert(summary.ReferenceHeadingIssues == 0, ...
    'Production files with non-unified reference headings: %d.', ...
    summary.ReferenceHeadingIssues);

declarations = summary.DeclarationRecords;
localAssertDeclaration(declarations, ...
    fullfile('+csrd', '+blocks', '+physical', '+modulate', '+analog', '+AM', 'DSBAM.m'), ...
    "DSBAM", "classdef", false);
localAssertDeclaration(declarations, ...
    fullfile('+csrd', '+blocks', '+physical', '+modulate', '+analog', '+AM', 'DSBAM.m'), ...
    "baseModulator", "function", true);
localAssertDeclaration(declarations, ...
    fullfile('+csrd', '+blocks', '+physical', '+modulate', '+analog', '+AM', 'DSBAM.m'), ...
    "genModulatorHandle", "function", true);
localAssertDeclaration(declarations, ...
    fullfile('+csrd', '+blocks', '+physical', '+modulate', 'BaseModulator.m'), ...
    "stepImpl", "function", true);

fprintf('  [OK] production files audited: %d\n', summary.FilesAudited);
fprintf('  [OK] production declarations audited: %d\n', summary.DeclarationsAudited);
fprintf('=== Phase 14 production bilingual comment audit PASSED ===\n');
end


function localAssertDeclaration(declarations, pathSuffix, name, kind, requireIo)
% localAssertDeclaration - Check one declaration-level audit sample.
% 中文说明：检查指定样本声明具备中英文说明和必要输入输出说明。
paths = string({declarations.Path});
names = string({declarations.Name});
kinds = string({declarations.Kind});
idx = endsWith(paths, string(pathSuffix)) & names == name & kinds == kind;
assert(any(idx), 'Missing declaration audit record for %s in %s.', ...
    name, pathSuffix);
hit = declarations(find(idx, 1, 'first'));
assert(hit.HasEnglishComment && hit.HasChineseComment, ...
    'Declaration %s in %s lacks bilingual comments.', name, pathSuffix);
if requireIo
    assert(hit.HasInputOutputComment, ...
        'Declaration %s in %s lacks bilingual input/output comments.', ...
        name, pathSuffix);
end
end
