function test_phase7_downstream_docs_readiness()
%TEST_PHASE7_DOWNSTREAM_DOCS_READINESS Phase 7 release docs regression.

here = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(here));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'tools'));
addpath(fullfile(projectRoot, 'tools', 'release'));
addpath(fullfile(projectRoot, 'examples'));

docs = run_csrd_downstream_docs_readiness('Verbose', false);
assert(docs.Success, 'Phase 7 downstream docs readiness failed.');
assert(numel(docs.Documentation) >= 4, ...
    'Expected schema, downstream, release notes, and executable example checks.');
assert(all([docs.Documentation.Matched]), ...
    'All Phase 7 document content checks must pass.');

outDir = tempname;
mkdir(outDir);
cleanup = onCleanup(@() localRemoveDir(outDir));
annotationPath = fullfile(outDir, 'annotation_v2_fixture.json');
cocoPath = fullfile(outDir, 'coco_fixture.json');
localWriteJson(annotationPath, localFixturePayload());

summary = read_annotation_v2_downstream(annotationPath, cocoPath);

assert(strcmp(summary.Schema, 'annotation-v2'), ...
    'Downstream example must use annotation v2 reader summary.');
assert(summary.NumFrames == 1, 'Expected one fixture frame.');
assert(summary.NumSources == 1, 'Expected one fixture source.');
assert(summary.NumCocoAnnotations == 1, ...
    'Expected one visible COCO annotation.');
assert(strcmp(summary.CocoCoordinateSystem, 'receiver_frequency_canvas'), ...
    'COCO export must preserve receiver-frequency canvas semantics.');
assert(isfile(cocoPath), 'Downstream example did not write COCO JSON.');

decoded = jsondecode(fileread(cocoPath));
assert(decoded.csrd_export.num_annotations == 1, ...
    'Written COCO JSON annotation count drifted.');

delete(cleanup);
end


function payload = localFixturePayload()
sourcePlane = struct( ...
    'OccupiedBandwidthHz', 1e6, ...
    'CenterFrequencyHz', 0, ...
    'SNRdB', 22, ...
    'TimeOccupancy', 0.75, ...
    'FrequencyOccupancy', 0.1, ...
    'MeasurementSemantics', 'receiver_view_isolated');

framePlane = struct( ...
    'OccupiedBandwidthHz', 1.1e6, ...
    'CenterFrequencyHz', 0, ...
    'TimeOccupancy', 0.75, ...
    'FrequencyOccupancy', 0.11, ...
    'MeasurementSemantics', 'post_rx_combined_pre_rfchain');

geometry = struct( ...
    'TxPositionM', [0 0 10], ...
    'TxVelocityMps', [0 0 0], ...
    'RxPositionM', [100 0 10], ...
    'RxVelocityMps', [0 0 0], ...
    'LinkDistanceM', 100);

design = struct( ...
    'PlannedCenterFrequencyHz', 2.4e9, ...
    'PlannedBandwidthHz', 1e6, ...
    'PlannedSampleRate', 5e6, ...
    'ModulationFamily', 'QPSK', ...
    'ModulationOrder', 4, ...
    'PayloadLengthBits', 1024, ...
    'NumTransmitAntennas', 1);

execution = struct( ...
    'ModulatedBandwidthHz', 1e6, ...
    'CenterFrequencyOffsetHz', 0, ...
    'SampleRate', 5e6, ...
    'ChannelModel', 'AWGN', ...
    'PathLossDB', 80, ...
    'AnalyticalSNRdB', 22, ...
    'AppliedSNRdB', 22, ...
    'DopplerShiftHz', 0, ...
    'RadialVelocityMps', 0, ...
    'GeometrySnapshot', geometry);

source = struct( ...
    'TxID', 'Tx1', ...
    'SegmentId', 1, ...
    'BurstId', 'Tx1-Burst1', ...
    'Truth', struct( ...
        'Design', design, ...
        'Execution', execution, ...
        'Measured', struct( ...
            'SourcePlane', sourcePlane, ...
            'FramePlane', framePlane)), ...
    'RFImpairments', struct(), ...
    'ReceiverView', struct( ...
        'ReceiverId', 'Rx1', ...
        'ProjectedCenterOffsetHz', 0, ...
        'ProjectedLowerEdgeHz', -5e5, ...
        'ProjectedUpperEdgeHz', 5e5, ...
        'IsVisible', true, ...
        'VisibilityReason', 'InBand'));

frame = struct( ...
    'FrameId', 1, ...
    'ReceiverID', 'Rx1', ...
    'ReceiverType', 'monitor', ...
    'SampleRate', 10e6, ...
    'ObservableRange', [-5e6 5e6], ...
    'Status', 'Success', ...
    'SignalSources', source);

payload = struct( ...
    'Frames', frame, ...
    'Header', struct( ...
        'Runtime', struct( ...
            'BlueprintHash', 'phase7-docs-fixture', ...
            'ValidatorVersion', 'phase7-test')));
end


function localWriteJson(path, payload)
fid = fopen(path, 'w');
assert(fid > 0, 'Could not open fixture JSON for writing.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(payload, 'PrettyPrint', true));
delete(cleanup);
end


function localRemoveDir(path)
if exist(path, 'dir') == 7
    rmdir(path, 's');
end
end
