function test_phase16_osm_raytracing_validation_config()
%TEST_PHASE16_OSM_RAYTRACING_VALIDATION_CONFIG Validate Phase 16 config.
% 中文说明：静态加载 Phase 16 正式配置，并 dry-run 覆盖矩阵构建，不生成正式数据。

fprintf('=== Phase 16 OSM RayTracing Validation Config Test ===\n');

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'tools'));

cfg = csrd.runtime.config_loader('csrd2025/csrd2025_osm_raytracing_validation.m');
assert(isfield(cfg, 'CoverageValidation') && cfg.CoverageValidation.Enable, ...
    'Phase 16 config must enable CoverageValidation.');
assert(strcmp(cfg.CoverageValidation.Mode, 'osm_raytracing_stress'), ...
    'Phase 16 config must select osm_raytracing_stress mode.');
assert(strcmp(cfg.Runner.Data.OutputDirectory, ...
    'CSRD2025_osm_raytracing_validation'), ...
    'Phase 16 config must write formal data under data/CSRD2025_osm_raytracing_validation.');
assert(isfield(cfg.CoverageValidation, 'OsmRayTracing') && ...
    cfg.CoverageValidation.OsmRayTracing.Enable, ...
    'Phase 16 config must enable OSM RayTracing stress cases.');
assert(cfg.CoverageValidation.Visualization.MinRectangles >= 9, ...
    'Phase 16 visual QA must require the 3 Tx x 3 burst rectangle set.');

summary = csrd.support.validation.runFullCoverageValidation( ...
    cfg, 'csrd2025/csrd2025_osm_raytracing_validation.m', ...
    projectRoot, 1, 1, 'DryRun', true);
names = string({summary.Records.Name});
assert(any(contains(names, "osm_rt_building_reg")), ...
    'Dry-run matrix did not build building OSM regulatory cases.');
assert(any(contains(names, "osm_rt_flatterrain_reg")), ...
    'Dry-run matrix did not build flat/no-building OSM regulatory cases.');
assert(any(contains(names, "osm_rt_building_mod")), ...
    'Dry-run matrix did not build building OSM modulation cases.');
assert(any(names == "osm_rt_building_multi_tx_multi_burst_visual"), ...
    'Dry-run matrix did not include the deterministic multi-burst visual case.');
assert(summary.CasesBuilt >= 60, ...
    'Phase 16 validation matrix should remain broader than Phase 13 full coverage.');

fprintf('  [OK] Phase 16 dry-run built %d cases.\n', summary.CasesBuilt);
fprintf('=== Phase 16 OSM RayTracing Validation Config Test Passed ===\n');
end
