function test_phase16_spectrogram_overlay_renderer()
%TEST_PHASE16_SPECTROGRAM_OVERLAY_RENDERER Smoke-test visual GT overlays.

fprintf('=== Phase 16 Spectrogram Overlay Renderer Test ===\n');

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'tools', 'visualization'));

fixtureRoot = fullfile(projectRoot, 'artifacts', 'tests', 'runs', ...
    'phase16_visualization_fixture', 'session_000001');
outputRoot = fullfile(projectRoot, 'artifacts', 'visual_checks', ...
    'phase16_renderer_test');
cleanupObj = onCleanup(@() localCleanup(fixtureRoot, outputRoot)); %#ok<NASGU>
mkdir(fullfile(fixtureRoot, 'scenarios'));
mkdir(fullfile(fixtureRoot, 'annotations'));
mkdir(outputRoot);

fs = 1e6;
duration = 0.01;
t = (0:round(fs * duration)-1)' / fs;
sig = exp(1j * 2 * pi * 120e3 * t) + 0.02 * randn(size(t));
rxFrame = struct('ReceiverID', 'Rx1', 'Signal', sig, ...
    'SampleRate', fs, 'Duration', duration);
scenarioData = {{rxFrame}}; %#ok<NASGU>
save(fullfile(fixtureRoot, 'scenarios', 'scenario_000001_data.mat'), ...
    'scenarioData');

payload = localAnnotationPayload(fs);
fid = fopen(fullfile(fixtureRoot, 'annotations', ...
    'scenario_000001_annotation.json'), 'w');
assert(fid > 0, 'Could not write Phase 16 annotation fixture.');
fprintf(fid, '%s', jsonencode(payload, 'PrettyPrint', true));
fclose(fid);

summary = render_csrd_spectrogram_overlays('DataRoot', fileparts(fixtureRoot), ...
    'OutputRoot', outputRoot, 'MaxImages', 1, 'RequireRectangles', true);
assert(summary.ImagesRendered == 1, 'Renderer should produce exactly one fixture image.');
assert(summary.RectanglesDrawn == 1, 'Renderer should draw one annotation rectangle.');
assert(exist(char(summary.Records(1).ImagePath), 'file') == 2, ...
    'Rendered PNG does not exist.');

fprintf('  [OK] Rendered %s.\n', summary.Records(1).ImagePath);
fprintf('=== Phase 16 Spectrogram Overlay Renderer Test Passed ===\n');
end


function payload = localAnnotationPayload(fs)
design = struct( ...
    'PlannedCenterFrequencyHz', 2.4e9, ...
    'PlannedBandwidthHz', 200e3, ...
    'PlannedSampleRate', fs, ...
    'ModulationFamily', 'QAM', ...
    'ModulationOrder', 16, ...
    'MessageSource', 'RandomBit', ...
    'IsDigital', true, ...
    'PayloadLengthBits', 1024, ...
    'NumTransmitAntennas', 1, ...
    'Regulatory', csrd.catalog.spectrum.RegulatoryValidator.emptyRegulatoryTruth());
execution = struct( ...
    'ModulatedBandwidthHz', 200e3, ...
    'AnalyticalBandwidthHz', 200e3, ...
    'CenterFrequencyOffsetHz', 120e3, ...
    'SampleRate', fs, ...
    'ChannelModel', 'RayTracing', ...
    'PathLossDB', 80, ...
    'AnalyticalSNRdB', 20, ...
    'AppliedSNRdB', 20, ...
    'DopplerShiftHz', 0, ...
    'RadialVelocityMps', 0, ...
    'GeometrySnapshot', struct( ...
        'TxPositionM', [0, 0, 20], ...
        'TxVelocityMps', [0, 0, 0], ...
        'RxPositionM', [100, 0, 10], ...
        'RxVelocityMps', [0, 0, 0], ...
        'LinkDistanceM', 100), ...
    'MapProfile', struct( ...
        'Mode', 'OSMBuildings', ...
        'HasBuildings', true, ...
        'ChannelModel', 'RayTracing'), ...
    'RayCount', 1, ...
    'ChannelFallback', '');
measured = struct( ...
    'SourcePlane', struct( ...
        'OccupiedBandwidthHz', 200e3, ...
        'CenterFrequencyHz', 120e3, ...
        'SNRdB', 20, ...
        'TimeOccupancy', 1, ...
        'FrequencyOccupancy', 0.2, ...
        'MeasurementSemantics', 'receiver_view_isolated'), ...
    'FramePlane', struct( ...
        'OccupiedBandwidthHz', 200e3, ...
        'CenterFrequencyHz', 120e3, ...
        'TimeOccupancy', 1, ...
        'FrequencyOccupancy', 0.2, ...
        'MeasurementSemantics', 'post_rx_combined_pre_rfchain'));
source = struct( ...
    'TxID', 'Tx1', ...
    'SegmentId', 'Tx1_seg001', ...
    'BurstId', 'Tx1_seg001_burst001', ...
    'Truth', struct('Design', design, 'Execution', execution, 'Measured', measured), ...
    'RFImpairments', struct(), ...
    'ReceiverView', struct( ...
        'ReceiverId', 'Rx1', ...
        'ProjectedCenterOffsetHz', 120e3, ...
        'ProjectedLowerEdgeHz', 20e3, ...
        'ProjectedUpperEdgeHz', 220e3, ...
        'IsVisible', true, ...
        'VisibilityReason', 'InBand'));
frame = struct( ...
    'FrameId', 1, ...
    'ReceiverID', 'Rx1', ...
    'ReceiverType', 'Simulation', ...
    'Position', [100; 0; 10], ...
    'SampleRate', fs, ...
    'ObservableRange', [-fs/2; fs/2], ...
    'NumSignalComponents', 1, ...
    'Status', 'Success', ...
    'SignalSources', source, ...
    'RxImpairments', struct());
payload = struct();
payload.Header.Runtime = struct('ScenarioId', 1, 'WorkerId', 1);
payload.Frames = frame;
end


function localCleanup(fixtureRoot, outputRoot)
if exist(fixtureRoot, 'dir')
    rmdir(fileparts(fixtureRoot), 's');
end
if exist(outputRoot, 'dir')
    rmdir(outputRoot, 's');
end
end
