function test_no_dead_code_phase21_performance_contracts()
%TEST_NO_DEAD_CODE_PHASE21_PERFORMANCE_CONTRACTS Static Phase 21 perf gates.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));

loggerCode = fileread(fullfile(root, '+csrd', '+runtime', '+logger', ...
    '+mlog', '@Logger', 'constructMessage.m'));
assert(contains(loggerCode, 'if obj.isLevelLogged(argA)') && ...
    contains(loggerCode, 'callerInfo = getCallerInfo();'), ...
    'CSRD:Phase21:LoggerHotPathGate', ...
    'Logger must gate caller stack lookup behind isLevelLogged().');

rrfCode = fileread(fullfile(root, '+csrd', '+blocks', '+physical', ...
    '+rxRadioFront', 'RRFSimulator.m'));
stepBody = localExtractFunctionBody(rrfCode, 'stepImpl');
assert(~contains(stepBody, 'release(obj.ThermalNoise)'), ...
    'CSRD:Phase21:RRFPerStepReleaseGate', ...
    'RRF stepImpl must not release ThermalNoise every frame.');
assert(~contains(stepBody, 'release(obj.SampleShifter)'), ...
    'CSRD:Phase21:RRFPerStepReleaseGate', ...
    'RRF stepImpl must not release SampleRateOffset every frame.');
assert(contains(rrfCode, 'SampleRateOffsetInfo'), ...
    'CSRD:Phase21:RRFSampleOffsetMetadataGate', ...
    'RRF identity/non-zero sample-rate offset path must export metadata.');

trfCode = fileread(fullfile(root, '+csrd', '+blocks', '+physical', ...
    '+txRadioFront', 'TRFSimulator.m'));
resampleBody = localExtractFunctionBody(trfCode, 'resampleToTarget');
assert(~contains(resampleBody, 'for antIdx'), ...
    'CSRD:Phase21:TRFColumnLoopGate', ...
    'TRF resampleToTarget must not reintroduce a per-antenna MATLAB loop.');
assert(contains(resampleBody, 'resample(inputSignal,') && ...
    contains(resampleBody, 'upsampleFactor, downsampleFactor'), ...
    'CSRD:Phase21:TRFMatrixResampleGate', ...
    'TRF resampleToTarget must use matrix resample for multi-antenna signals.');

rxCode = fileread(fullfile(root, '+csrd', '+core', '@ChangShuo', ...
    'private', 'processReceiverProcessing.m'));
assert(contains(rxCode, 'measureSignalSummary'), ...
    'CSRD:Phase21:MeasurementSummaryGate', ...
    'Receiver annotation path must use the one-pass measurement summary.');

defaultCfg = fileread(fullfile(root, 'config', 'csrd2025', 'csrd2025.m'));
assert(contains(defaultCfg, "config.Logging.Policy = 'LargeMC'") && ...
    contains(defaultCfg, "config.Logging.Progress.Mode = 'Summary'") && ...
    contains(defaultCfg, 'PrettyPrintAnnotations = false'), ...
    'CSRD:Phase21:DefaultPerformancePolicyGate', ...
    'Default csrd2025 config must keep LargeMC logging and compact JSON.');
end

function body = localExtractFunctionBody(code, functionName)
pattern = sprintf('function[^\\n]*%s\\s*\\(', functionName);
startIdx = regexp(code, pattern, 'once');
assert(~isempty(startIdx), 'CSRD:Phase21:StaticGateParseFailed', ...
    'Could not find function %s.', functionName);
nextIdx = regexp(code(startIdx + 1:end), '\n\s*function\s+', 'once');
if isempty(nextIdx)
    body = code(startIdx:end);
else
    body = code(startIdx:(startIdx + nextIdx - 1));
end
end
