function test_bandwidth_consistency()
    % test_bandwidth_consistency - Verify scenario bandwidth targets reach the modulator.

    fprintf('=== Bandwidth Consistency Test ===\n');

    projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    addpath(projectRoot);
    csrd.utils.logger.GlobalLogManager.reset();
    rng(1234);

    masterConfig = csrd.utils.config_loader('csrd2025/csrd2025.m');
    masterConfig.Log.Level = 'ERROR';
    masterConfig.Log.SaveToFile = false;
    masterConfig.Log.DisplayInConsole = false;
    csrd.utils.logger.GlobalLogManager.initialize(masterConfig.Log);

    factory = csrd.factories.ModulationFactory('Config', masterConfig.Factories.Modulation);
    cleanupObj = onCleanup(@() release(factory)); %#ok<NASGU>
    setup(factory);

    inputBits = repmat([0; 1; 1; 0; 1; 0; 0; 1], 6000, 1);
    placement.TargetBandwidth = 4e6;
    expectedSampleRate = placement.TargetBandwidth / 1.25 * 4;

    pskConfig = struct( ...
        'TypeID', 'PSK', ...
        'Type', 'PSK', ...
        'Order', 4, ...
        'RolloffFactor', 0.25, ...
        'SamplesPerSymbol', 4);
    pskOut = step(factory, inputBits, 1, "TxBW", 1, pskConfig, placement);
    assert(abs(pskOut.SampleRate - expectedSampleRate) < 1, ...
        'PSK sample rate should reflect target bandwidth and SPS.');
    assert(isfield(pskOut, 'ModulatorConfig') && isfield(pskOut.ModulatorConfig, 'beta') && ...
        abs(pskOut.ModulatorConfig.beta - 0.25) < 1e-12, ...
        'PSK rolloff factor should be propagated into ModulatorConfig.beta.');
    assert(isfield(pskOut.ModulatorConfig, 'span') && pskOut.ModulatorConfig.span == 10, ...
        'PSK pulse-shaping span should be deterministically initialized.');
    assert(strcmp(string(pskOut.ModulatorConfig.SymbolOrder), "gray"), ...
        'PSK symbol order should be deterministically initialized.');
    assert(pskOut.Bandwidth > 0, 'PSK modulation should report positive occupied bandwidth.');
    fprintf('  [OK] PSK modulation config propagated (BW=%.0f Hz).\n', pskOut.Bandwidth);

    qamConfig = struct( ...
        'TypeID', 'QAM', ...
        'Type', 'QAM', ...
        'Order', 16, ...
        'RolloffFactor', 0.25, ...
        'SamplesPerSymbol', 4);
    qamOut = step(factory, inputBits, 1, "TxBW", 2, qamConfig, placement);
    assert(abs(qamOut.SampleRate - expectedSampleRate) < 1, ...
        'QAM sample rate should reflect target bandwidth and SPS.');
    assert(isfield(qamOut, 'ModulatorConfig') && isfield(qamOut.ModulatorConfig, 'beta') && ...
        abs(qamOut.ModulatorConfig.beta - 0.25) < 1e-12, ...
        'QAM rolloff factor should be propagated into ModulatorConfig.beta.');
    assert(isfield(qamOut.ModulatorConfig, 'span') && qamOut.ModulatorConfig.span == 10, ...
        'QAM pulse-shaping span should be deterministically initialized.');
    assert(strcmp(string(qamOut.ModulatorConfig.SymbolOrder), "gray"), ...
        'QAM symbol order should be deterministically initialized.');
    assert(qamOut.Bandwidth > 0, 'QAM modulation should report positive occupied bandwidth.');
    fprintf('  [OK] QAM modulation config propagated (BW=%.0f Hz).\n', qamOut.Bandwidth);

    fprintf('=== Bandwidth Consistency Test Passed ===\n');
end
