function results = run_csrd_coverage_smoke(varargin)
%RUN_CSRD_COVERAGE_SMOKE Fast multi-region generation regression guard.
% Generates one AWGN scenario for the first few bands of every supported
% region and asserts none fail, so a silent multi-region generation
% regression (wrong region routing, SDR frame-contract mismatch, empty
% zero-source scene) cannot pass CI unnoticed.
% Inputs: see signature arguments and local validation.
% Outputs: see signature return values and contract fields.

p = inputParser;
addParameter(p, 'Seed', 74100, @(x) isnumeric(x) && isscalar(x));
addParameter(p, 'MaxBandsPerRegion', 4, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);
parse(p, varargin{:});

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(projectRoot, 'tools', 'coverage'));

res = run_generation_coverage( ...
    'ScenariosPerCell', 1, ...
    'ChannelModels', {'AWGN'}, ...
    'MaxBandsPerRegion', p.Results.MaxBandsPerRegion, ...
    'Seed', p.Results.Seed);

statuses = {res.Status};
problems = res(~ismember(statuses, {'OK', 'NoCompatibleSdr'}));

% Bound disk: drop the artifacts generated by this smoke run.
runRoot = fullfile(projectRoot, 'artifacts', 'coverage', ...
    sprintf('generation_%d', p.Results.Seed));
if exist(runRoot, 'dir'); rmdir(runRoot, 's'); end

results = struct( ...
    'Success', isempty(problems), ...
    'Total', numel(res), ...
    'OK', sum(strcmp(statuses, 'OK')), ...
    'NoCompatibleSdr', sum(strcmp(statuses, 'NoCompatibleSdr')), ...
    'Problems', numel(problems));

if ~isempty(problems)
    first = problems(1);
    error('CSRD:CI:CoverageSmokeFailed', ...
        '%d/%d coverage cells failed (e.g. %s/%s %s: %s).', ...
        numel(problems), numel(res), first.Region, first.BandId, ...
        first.Status, first.ErrorMessage);
end

fprintf('  Coverage smoke: %d cells, %d OK, %d no-compatible-SDR.\n', ...
    results.Total, results.OK, results.NoCompatibleSdr);
end
