function profile = ISM24_WiFi24()
%ISM24_WIFI24 v0 band profile: 2.4 GHz ISM / WiFi (2400-2483.5 MHz).
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis A (row 3).
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.A.

    profile = struct( ...
        'FrequencyRangeHz',              [2400e6 2483.5e6], ...
        'RecommendedBandwidthsHz',       {{20e6, 40e6}}, ...
        'RecommendedModulationFamilies', {{'OFDM','SC-FDMA'}}, ...
        'TemporalPattern',               'Burst', ...
        'BurstOnTimeRangeMs',            [1 10], ...
        'BurstOffTimeRangeMs',           [1 100], ...
        'RecommendedTxAntennas',         [1 4], ...
        'TypicalNoiseFigureDb',          7, ...
        'RecommendedRxProfiles',         {{'LabAnalyzer_160MHz','DenseArrayStation_200MHz'}});
end
