function profile = ISM58_WiFi5()
%ISM58_WIFI5 v0 band profile: 5 GHz ISM / WiFi 5 (5150-5350 / 5725-5850 MHz).
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis A (row 4).
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.A.
%
% NOTE: WiFi 5 occupies two non-contiguous sub-bands (lower UNII-1/UNII-2
% and upper UNII-3). FrequencyRangeHz reports the outer envelope; the
% Validator's frequency-band coverage check should use SubRangesHz when
% present.

    profile = struct( ...
        'FrequencyRangeHz',              [5150e6 5850e6], ...
        'SubRangesHz',                   {{[5150e6 5350e6], [5725e6 5850e6]}}, ...
        'RecommendedBandwidthsHz',       {{20e6, 40e6, 80e6}}, ...
        'RecommendedModulationFamilies', {{'OFDM'}}, ...
        'TemporalPattern',               'Burst', ...
        'BurstOnTimeRangeMs',            [1 10], ...
        'BurstOffTimeRangeMs',           [1 100], ...
        'RecommendedTxAntennas',         [1 4], ...
        'TypicalNoiseFigureDb',          8, ...
        'RecommendedRxProfiles',         {{'LabAnalyzer_160MHz','DenseArrayStation_200MHz'}});
end
