function profile = NR_n28()
%NR_N28 v0 band profile: 5G NR band n28 (703-803 MHz).
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis A (row 5,
% labelled '5GNR_n28'). Renamed to 'NR_n28' to match §16.8.1 directory
% layout.
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.A.

    profile = struct( ...
        'FrequencyRangeHz',              [703e6 803e6], ...
        'RecommendedBandwidthsHz',       {{5e6, 10e6, 15e6, 20e6}}, ...
        'RecommendedModulationFamilies', {{'OFDM'}}, ...
        'TemporalPattern',               'Continuous', ...
        'BurstOnTimeRangeMs',            [], ...
        'BurstOffTimeRangeMs',           [], ...
        'RecommendedTxAntennas',         [1 4], ...
        'TypicalNoiseFigureDb',          6, ...
        'RecommendedRxProfiles',         {{'PortableMonitor_40MHz','LabAnalyzer_160MHz'}});
end
