function profile = NR_n79()
%NR_N79 v0 band profile: 5G NR band n79 (4800-4960 MHz).
%
% Source numbers: docs/audits/2026-04-...refactor.md §5.bis A (row 7).
% Schema:        docs/audits/phases/phase-2-blueprint.md §3.1.3.A.

    profile = struct( ...
        'FrequencyRangeHz',              [4800e6 4960e6], ...
        'RecommendedBandwidthsHz',       {{40e6, 60e6, 100e6}}, ...
        'RecommendedModulationFamilies', {{'OFDM'}}, ...
        'TemporalPattern',               'Continuous', ...
        'BurstOnTimeRangeMs',            [], ...
        'BurstOffTimeRangeMs',           [], ...
        'RecommendedTxAntennas',         [1 4], ...
        'TypicalNoiseFigureDb',          6, ...
        'RecommendedRxProfiles',         {{'LabAnalyzer_160MHz','DenseArrayStation_200MHz'}});
end
