classdef ChannelFactoryNoWarningDowngradeTest < matlab.unittest.TestCase
    % ChannelFactoryNoWarningDowngradeTest - Channel config failures are hard.

    methods (Test)
        function assignmentFailuresAreNotWarnings(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            code = fileread(fullfile(root, '+csrd', '+factories', ...
                'ChannelFactory.m'));

            banned = { ...
                'Could not set channel property', ...
                'Could not update channel Distance', ...
                'Could not set channel prop', ...
                'Could not update NumTransmitAntennas', ...
                'Could not update NumReceiveAntennas'};
            for k = 1:numel(banned)
                testCase.verifyFalse(contains(code, ...
                    ['obj.logger.warning(''', banned{k}]), ...
                    sprintf('ChannelFactory still downgrades "%s" to warning.', ...
                        banned{k}));
            end
        end
    end
end
