classdef ChannelFactoryAppliedSNRTest < matlab.unittest.TestCase
    %CHANNELFACTORYAPPLIEDSNRTEST SNR metadata contract for non-AWGN channels.

    methods (Test)
        function mimoChannelCarriesAppliedSnrFromLinkBudget(testCase)
            cfg = struct();
            cfg.ChannelModels.Rayleigh = struct( ...
                'handle', 'csrd.blocks.physical.channel.MIMO', ...
                'Config', struct( ...
                    'FadingDistribution', 'Rayleigh', ...
                    'MaximumDopplerShift', 0, ...
                    'PathDelays', 0, ...
                    'AveragePathGains', 0, ...
                    'Seed', 73));
            cfg.LinkBudget = struct( ...
                'NoiseBandwidth', 1e6, ...
                'NoiseFigure', 6, ...
                'ThermalNoisePSD', -174, ...
                'MinDistance', 0.01, ...
                'EnableDistanceBasedSNR', true);
            cfg.DefaultModels.Statistical = 'Rayleigh';
            cfg.NoValidPathFallback = 'FreeSpaceAttenuation';

            factory = csrd.factories.ChannelFactory('Config', cfg);
            setup(factory);
            cleanupObj = onCleanup(@() localRelease(factory)); %#ok<NASGU>

            input = struct( ...
                'Signal', complex(ones(256, 1), zeros(256, 1)), ...
                'SampleRate', 1e6, ...
                'StartTime', 0);
            txInfo = struct( ...
                'ID', 'Tx1', ...
                'Position', [0, 0, 10], ...
                'Power', 20, ...
                'AntennaGain', 0, ...
                'NumTransmitAntennas', 1);
            rxInfo = struct( ...
                'ID', 'Rx1', ...
                'Position', [100, 0, 10], ...
                'RealCarrierFrequency', 2.4e9, ...
                'ObservableRange', [-0.5e6, 0.5e6], ...
                'SampleRate', 1e6, ...
                'AntennaGain', 0, ...
                'NumAntennas', 1);
            linkInfo = struct( ...
                'ChannelModel', 'Rayleigh', ...
                'BurstId', 'Tx1.Burst1', ...
                'MapProfile', struct('Mode', 'Statistical'));

            out = step(factory, input, 1, txInfo, rxInfo, linkInfo);

            testCase.verifyTrue(isfield(out, 'ComputedSNR'));
            testCase.verifyTrue(isfield(out, 'AppliedSNRdB'));
            testCase.verifyEqual(out.AppliedSNRdB, out.ComputedSNR, ...
                'AbsTol', 1e-9);
            testCase.verifyEqual(out.ChannelModel, 'Rayleigh');
        end

        function osmMapProfileUsesMeterPositionsForLinkDistance(testCase)
            cfg = struct();
            cfg.ChannelModels.Rayleigh = struct( ...
                'handle', 'csrd.blocks.physical.channel.MIMO', ...
                'Config', struct( ...
                    'FadingDistribution', 'Rayleigh', ...
                    'MaximumDopplerShift', 0, ...
                    'PathDelays', 0, ...
                    'AveragePathGains', 0, ...
                    'Seed', 74));
            cfg.LinkBudget = struct( ...
                'NoiseBandwidth', 1e6, ...
                'NoiseFigure', 6, ...
                'ThermalNoisePSD', -174, ...
                'MinDistance', 0.01, ...
                'EnableDistanceBasedSNR', true);
            cfg.DefaultModels.Statistical = 'Rayleigh';
            cfg.NoValidPathFallback = 'FreeSpaceAttenuation';

            factory = csrd.factories.ChannelFactory('Config', cfg);
            setup(factory);
            cleanupObj = onCleanup(@() localRelease(factory)); %#ok<NASGU>

            input = struct( ...
                'Signal', complex(ones(128, 1), zeros(128, 1)), ...
                'SampleRate', 1e6, ...
                'StartTime', 0);
            txInfo = struct( ...
                'ID', 'Tx1', ...
                'Position', [0, 0, 10], ...
                'PositionUnit', 'meters', ...
                'Power', 20, ...
                'AntennaGain', 0, ...
                'NumTransmitAntennas', 1);
            rxInfo = struct( ...
                'ID', 'Rx1', ...
                'Position', [100, 0, 10], ...
                'PositionUnit', 'meters', ...
                'RealCarrierFrequency', 2.4e9, ...
                'ObservableRange', [-0.5e6, 0.5e6], ...
                'SampleRate', 1e6, ...
                'AntennaGain', 0, ...
                'NumAntennas', 1);
            linkInfo = struct( ...
                'ChannelModel', 'Rayleigh', ...
                'BurstId', 'Tx1.Burst1', ...
                'MapProfile', struct('Mode', 'OSMBuildings'));

            out = step(factory, input, 1, txInfo, rxInfo, linkInfo);

            testCase.verifyEqual(out.LinkDistance, 100, 'AbsTol', 1e-9);
        end
    end
end

function localRelease(obj)
if isLocked(obj)
    release(obj);
end
end
