classdef ConvertCsrdToCocoTest < matlab.unittest.TestCase
    %CONVERTCSRDTOCOCOTEST Phase 6 COCO v2 converter contract.

    methods (TestMethodSetup)
        function addToolPath(testCase)
            here = fileparts(mfilename('fullpath'));
            projectRoot = fileparts(fileparts(here));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, 'tools')));
        end
    end

    methods (Test)
        function convertsVisibleSourceToFrequencyCanvasCoco(testCase)
            payload = localValidPayload();

            coco = convert_csrd_to_coco(payload, '', 'ImageWidth', 1000);

            testCase.verifyEqual(coco.info.source_schema, 'annotation');
            testCase.verifyEqual(numel(coco.images), 1);
            testCase.verifyEqual(coco.images.width, 1000);
            testCase.verifyEqual(coco.images.height, 1);
            testCase.verifyEqual(numel(coco.categories), 1);
            testCase.verifyEqual(coco.categories.name, 'QPSK');
            testCase.verifyEqual(numel(coco.annotations), 1);
            testCase.verifyEqual(coco.annotations.bbox, ...
                [450, 0, 100, 1], 'AbsTol', 1e-9);
            testCase.verifyEqual(coco.annotations.csrd.source_fields.category, ...
                'Truth.Design.ModulationFamily');
            testCase.verifyEqual(coco.annotations.csrd.source_fields.bbox_width_hz, ...
                'Truth.Measured.SourcePlane.OccupiedBandwidthHz');
            testCase.verifyEqual( ...
                coco.annotations.csrd.measured.SourcePlane.TimeOccupancy, 0.5);
        end

        function writesJsonFile(testCase)
            payload = localValidPayload();
            outDir = tempname;
            testCase.addTeardown(@() localRemoveDir(outDir));
            outPath = fullfile(outDir, 'coco.json');

            coco = convert_csrd_to_coco(payload, outPath, 'ImageWidth', 200);

            testCase.verifyTrue(isfile(outPath));
            decoded = jsondecode(fileread(outPath));
            testCase.verifyEqual(decoded.csrd_export.num_annotations, 1);
            testCase.verifyEqual(decoded.images.width, 200);
            testCase.verifyEqual(coco.csrd_export.num_annotations, 1);
            testCase.verifyTrue(isfield(coco.csrd_export, 'sanitize_manifest'));
        end

        function skipsInvisibleSourcesWithoutBBox(testCase)
            payload = localValidPayload();
            payload.Frames{1}{1}.SignalSources.ReceiverView.IsVisible = false;
            payload.Frames{1}{1}.SignalSources.ReceiverView.VisibilityReason = ...
                'OutOfBand';

            coco = convert_csrd_to_coco(payload);

            testCase.verifyEmpty(coco.annotations);
            testCase.verifyEqual(coco.csrd_export.num_skipped_sources, 1);
            testCase.verifyEqual(coco.csrd_export.skipped_sources.visibility_reason, ...
                'OutOfBand');
        end

        function rejectsLegacyV1TopLevelFields(testCase)
            payload = localValidPayload();
            payload.Frames{1}{1}.SignalSources.Planned = struct();

            testCase.verifyError(@() convert_csrd_to_coco(payload), ...
                'CSRD:AnnotationV2:LegacyFieldPresent');
        end

        function rejectsMissingMeasuredBandwidth(testCase)
            payload = localValidPayload();
            payload.Frames{1}{1}.SignalSources.Truth.Measured.SourcePlane. ...
                OccupiedBandwidthHz = NaN;

            testCase.verifyError(@() convert_csrd_to_coco(payload), ...
                'CSRD:Tools:CocoMissingFiniteScalar');
        end
    end
end


function payload = localValidPayload()
sourcePlane = struct( ...
    'OccupiedBandwidthHz', 1e6, ...
    'CenterFrequencyHz', 0, ...
    'SNRdB', 20, ...
    'TimeOccupancy', 0.5, ...
    'FrequencyOccupancy', 0.1, ...
    'MeasurementSemantics', 'receiver_view_isolated');

framePlane = struct( ...
    'OccupiedBandwidthHz', 1.2e6, ...
    'CenterFrequencyHz', 1e5, ...
    'TimeOccupancy', 0.8, ...
    'FrequencyOccupancy', 0.12, ...
    'MeasurementSemantics', 'post_rx_combined_pre_rfchain');

geometry = struct( ...
    'TxPositionM', [0 0 10], ...
    'TxVelocityMps', [1 0 0], ...
    'RxPositionM', [100 0 10], ...
    'RxVelocityMps', [0 0 0], ...
    'LinkDistanceM', 100);

design = struct( ...
    'PlannedCenterFrequencyHz', 2.4e9, ...
    'PlannedBandwidthHz', 1e6, ...
    'PlannedSampleRate', 5e6, ...
    'ModulationFamily', 'QPSK', ...
    'ModulationOrder', 4, ...
    'MessageSource', 'RandomBit', ...
    'IsDigital', true, ...
    'PayloadLengthBits', 1024, ...
    'NumTransmitAntennas', 1);

execution = struct( ...
    'ModulatedBandwidthHz', 1e6, ...
    'CenterFrequencyOffsetHz', 0, ...
    'SampleRate', 5e6, ...
    'ChannelModel', 'AWGN', ...
    'PathLossDB', 80, ...
    'AnalyticalSNRdB', 20, ...
    'AppliedSNRdB', 20, ...
    'DopplerShiftHz', 1.5, ...
    'RadialVelocityMps', 0.2, ...
    'GeometrySnapshot', geometry);

source = struct( ...
    'TxID', 'Tx1', ...
    'SegmentId', 1, ...
    'BurstId', 'Burst1', ...
    'Truth', struct( ...
        'Design', design, ...
        'Execution', execution, ...
        'Measured', struct( ...
            'SourcePlane', sourcePlane, ...
            'FramePlane', framePlane)), ...
    'RFImpairments', struct(), ...
    'ReceiverView', struct( ...
        'ReceiverId', 'Rx1', ...
        'ProjectedCenterOffsetHz', 0, ...
        'ProjectedLowerEdgeHz', -5e5, ...
        'ProjectedUpperEdgeHz', 5e5, ...
        'IsVisible', true, ...
        'VisibilityReason', 'InBand'));

frame = struct( ...
    'FrameId', 1, ...
    'ReceiverID', 'Rx1', ...
    'ReceiverType', 'monitor', ...
    'SampleRate', 10e6, ...
    'ObservableRange', [-5e6 5e6], ...
    'Status', 'Success', ...
    'SignalSources', source);

payload = struct( ...
    'Frames', {{ {frame} }}, ...
    'Header', struct( ...
        'Runtime', struct( ...
            'BlueprintHash', 'abc123', ...
            'ValidatorVersion', 'phase6-test')));
end


function localRemoveDir(path)
if exist(path, 'dir') == 7
    rmdir(path, 's');
end
end
