classdef MeasurementFailureVisibilityTest < matlab.unittest.TestCase
    % MeasurementFailureVisibilityTest - Live measurement failures are visible.
    % 中文说明：有信号测量失败必须抛 CSRD:Measurement，空信号才允许 NaN。

    methods (Test)
        function productionCodeThrowsMeasurementErrors(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            code = fileread(fullfile(root, '+csrd', '+core', '@ChangShuo', ...
                'private', 'processReceiverProcessing.m'));

            required = { ...
                'CSRD:Measurement:SourceOBWFailed', ...
                'CSRD:Measurement:SourceCenterFrequencyFailed', ...
                'CSRD:Measurement:SourceEnvelopeFailed', ...
                'CSRD:Measurement:FrameOBWFailed', ...
                'MeasurementStatus = ''NoSignal''', ...
                'MeasurementStatus = ''Measured'''};
            for k = 1:numel(required)
                testCase.verifyTrue(contains(code, required{k}), ...
                    sprintf('Missing measurement visibility marker: %s', required{k}));
            end
        end
    end
end
