classdef OsmMapResourceCacheContractTest < matlab.unittest.TestCase
    %OSMMAPRESOURCECACHECONTRACTTEST Phase 22 OSM heavy-resource contract.

    methods (Test)

        function physicalEnvironmentDoesNotCreateBuildingSiteviewer(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            sourcePath = fullfile(root, '+csrd', '+blocks', '+scenario', ...
                '@PhysicalEnvironmentSimulator', 'private', 'initializeOSMMap.m');
            code = fileread(sourcePath);

            testCase.verifyFalse(contains(code, 'siteviewer('), ...
                ['PhysicalEnvironmentSimulator must not create the heavy ', ...
                 'OSM siteviewer; RayTracing owns that resource.']);
            testCase.verifyTrue(contains(code, 'LazyRayTracingSiteViewer'), ...
                'MapProfile must document that RayTracing lazily owns the map handle.');
            testCase.verifyTrue(contains(code, ...
                'NoOnlineTerrainForBatchRayTracing'), ...
                ['OSM building MapProfile must declare that batch RayTracing ', ...
                 'does not rely on MATLAB online terrain data.']);
        end

        function rayTracingCachesSitesRaysAndMapHandle(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            sourcePath = fullfile(root, '+csrd', '+blocks', '+physical', ...
                '+channel', 'RayTracing.m');
            code = fileread(sourcePath);

            testCase.verifyTrue(contains(code, 'sitePairCache'), ...
                'RayTracing must cache txsite/rxsite pairs across bursts.');
            testCase.verifyTrue(contains(code, 'raySetCache'), ...
                'RayTracing must cache raytrace results for stable link geometry.');
            testCase.verifyTrue(contains(code, 'RaytraceCall'), ...
                'RayTracing profile counters must expose raytrace calls.');
            testCase.verifyTrue(contains(code, 'osmSiteViewerCache'), ...
                'RayTracing must use the process-local OSM siteviewer cache.');
            testCase.verifyTrue(contains(code, ...
                'RayTracing.SiteviewerLocalCacheInvalidated'), ...
                ['RayTracing must reject stale/non-object local map handles ', ...
                 'before passing Map to raytrace.']);

            cachePath = fullfile(root, '+csrd', '+runtime', '+map', ...
                'osmSiteViewerCache.m');
            cacheCode = fileread(cachePath);
            testCase.verifyTrue(contains(cacheCode, 'SiteviewerCacheHit'), ...
                'Shared OSM cache must expose siteviewer cache-hit counters.');
            testCase.verifyTrue(contains(cacheCode, '''Terrain'', ''none'''), ...
                ['Shared OSM siteviewer creation must explicitly disable ', ...
                 'gmted2010 terrain so long runs do not fail on terrain I/O.']);
        end

        function runnerClearsSharedSiteviewerCache(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            sourcePath = fullfile(root, '+csrd', 'SimulationRunner.m');
            code = fileread(sourcePath);

            testCase.verifyGreaterThanOrEqual( ...
                count(string(code), "osmSiteViewerCache('clear')"), 2, ...
                ['SimulationRunner must clear the shared OSM cache at run ', ...
                 'boundaries so hidden viewers do not leak across runs.']);
            testCase.verifyTrue(contains(code, "osmSiteViewerCache('retain', true)"));
            testCase.verifyTrue(contains(code, "osmSiteViewerCache('retain', false)"));
        end

    end
end
