classdef RayTracingBatchEquivalenceTest < matlab.unittest.TestCase
    %RAYTRACINGBATCHEQUIVALENCETEST Phase 21 RayTracing cache contract.

    methods (Test)

        function channelFactoryCachesRayTracingByMapProfile(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            sourcePath = fullfile(root, '+csrd', '+factories', 'ChannelFactory.m');
            code = fileread(sourcePath);

            testCase.verifyTrue(contains(code, 'Phase 21'), ...
                'ChannelFactory should document the Phase 21 RayTracing cache policy.');
            testCase.verifyTrue(contains(code, 'Map=%s|File=%s|Terrain=%s'), ...
                'RayTracing cache key must be map/profile scoped.');
            testCase.verifyTrue(contains(code, 'cacheKey = sprintf(''%s|Tx=%s|Rx=%s'''), ...
                'Non-RayTracing channels must remain per Tx/Rx cached.');
        end

        function rayTracingBlockCachesMapResources(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            sourcePath = fullfile(root, '+csrd', '+blocks', '+physical', ...
                '+channel', 'RayTracing.m');
            code = fileread(sourcePath);

            testCase.verifyTrue(contains(code, 'siteViewerCache'), ...
                'OSM siteviewer construction must be cached per OSM file.');
            testCase.verifyTrue(contains(code, 'propagationModelCache'), ...
                'Propagation model construction must be cached per map/profile.');
            testCase.verifyTrue(contains(code, 'precomputeFrameRays'), ...
                'RayTracing must expose frame-level batched ray precompute.');
            testCase.verifyTrue(contains(code, 'BatchedRaytraceCall'), ...
                'RayTracing must record batched raytrace performance events.');
        end

        function channelPropagationRequestsFramePrecompute(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            channelFactoryPath = fullfile(root, '+csrd', '+factories', ...
                'ChannelFactory.m');
            propagationPath = fullfile(root, '+csrd', '+core', '@ChangShuo', ...
                'private', 'processChannelPropagation.m');
            channelFactoryCode = fileread(channelFactoryPath);
            propagationCode = fileread(propagationPath);

            testCase.verifyTrue(contains(channelFactoryCode, ...
                'precomputeRayTracingFrame'), ...
                'ChannelFactory must provide frame-level RayTracing precompute.');
            testCase.verifyTrue(contains(propagationCode, ...
                'precomputeRayTracingFrame'), ...
                'processChannelPropagation must call RayTracing precompute before segment loops.');
            testCase.verifyTrue(contains(propagationCode, ...
                'localActiveTxInfosForChannelPrecompute'), ...
                ['RayTracing precompute must only include Tx entries that ', ...
                 'have live signal segments in the current frame.']);
            testCase.verifyTrue(contains(propagationCode, ...
                'localTxHasLiveSignalSegment'), ...
                ['Inactive Tx entries must not trigger expensive OSM ', ...
                 'raytrace work.']);
        end

    end
end
