classdef ReadAnnotationGeometryRoundTripTest < matlab.unittest.TestCase
    % ReadAnnotationGeometryRoundTripTest
    %
    % A GeometrySnapshot vector that contains NaN serialises to JSON null and
    % decodes back as a CELL, not a double, which crashes downstream
    % double()/norm(). readAnnotation must coerce it back to a numeric vector.

    methods (Test)

        function nanGeometryVectorRoundTripsAsDouble(testCase)
            payload = localValidPayload();
            % Force an unknown (NaN) geometry vector on the source -- the
            % reachable buildExecutionTruth default when position is unset.
            payload.Frames{1}{1}.SignalSources{1}.Truth.Execution.GeometrySnapshot.RxPositionM = ...
                [NaN, NaN, NaN];

            outDir = tempname;
            mkdir(outDir);
            testCase.addTeardown(@() rmdir(outDir, 's'));
            jsonPath = fullfile(outDir, 'annotation.json');

            sanitized = csrd.pipeline.annotation.sanitizeForJson(payload);
            fid = fopen(jsonPath, 'w');
            fprintf(fid, '%s', jsonencode(sanitized));
            fclose(fid);

            reader = csrd.pipeline.annotation.readAnnotation(jsonPath, ...
                'RequireSources', true);
            geom = reader.Sources{1}.Truth.Execution.GeometrySnapshot;

            % The corrupted cell must be coerced back to a numeric double vector
            % with the missing entries restored to NaN, and norm() must not throw.
            testCase.verifyClass(geom.RxPositionM, 'double');
            testCase.verifyEqual(numel(geom.RxPositionM), 3);
            testCase.verifyTrue(all(isnan(geom.RxPositionM)));
            testCase.verifyWarningFree(@() norm(double(geom.RxPositionM)));
            % A finite geometry vector still round-trips as a plain double.
            testCase.verifyClass(geom.TxPositionM, 'double');
            testCase.verifyEqual(double(geom.TxPositionM(:)'), [0 0 10], ...
                'AbsTol', 1e-9);
        end

    end
end

function payload = localValidPayload()
sourcePlane = struct('OccupiedBandwidthHz', 1e6, 'CenterFrequencyHz', 0, ...
    'SNRdB', 20, 'TimeOccupancy', 0.5, 'FrequencyOccupancy', 0.1, ...
    'MeasurementSemantics', 'receiver_view_isolated', 'MeasurementStatus', 'Measured');
framePlane = struct('OccupiedBandwidthHz', 1.2e6, 'CenterFrequencyHz', 1e5, ...
    'TimeOccupancy', 0.8, 'FrequencyOccupancy', 0.12, ...
    'MeasurementSemantics', 'post_rx_combined_pre_rfchain', 'MeasurementStatus', 'Measured');
geometry = struct('TxPositionM', [0 0 10], 'TxVelocityMps', [1 0 0], ...
    'RxPositionM', [100 0 10], 'RxVelocityMps', [0 0 0], 'LinkDistanceM', 100);
design = struct('PlannedCenterFrequencyHz', 0, 'PlannedBandwidthHz', 1e6, ...
    'PlannedSampleRate', 5e6, 'ModulationFamily', 'QPSK', 'ModulationOrder', 4, ...
    'MessageSource', 'RandomBit', 'IsDigital', true, 'PayloadLengthBits', 1024, ...
    'NumTransmitAntennas', 1);
execution = struct('ModulatedBandwidthHz', 1e6, 'CenterFrequencyOffsetHz', 0, ...
    'SampleRate', 5e6, 'ChannelModel', 'AWGN', 'PathLossDB', 80, ...
    'AnalyticalSNRdB', 20, 'AppliedSNRdB', 20, 'DopplerShiftHz', 1.5, ...
    'RadialVelocityMps', 0.2, 'StartTimeSec', 0, 'EndTimeSec', 1e-3, ...
    'DurationSec', 1e-3, 'FrameStartSample', 0, 'FrameEndSample', 5000, ...
    'FrameSampleCount', 5000, 'FrameLengthSamples', 5000, 'GeometrySnapshot', geometry);
source = struct('TxID', 'Tx1', 'SegmentId', 1, 'BurstId', 'Burst1', ...
    'Truth', struct('Design', design, 'Execution', execution, ...
        'Measured', struct('SourcePlane', sourcePlane, 'FramePlane', framePlane)), ...
    'RFImpairments', struct(), ...
    'ReceiverView', struct('ReceiverId', 'Rx1', 'ProjectedCenterOffsetHz', 0, ...
        'ProjectedLowerEdgeHz', -5e5, 'ProjectedUpperEdgeHz', 5e5, ...
        'IsVisible', true, 'VisibilityReason', 'InBand'));
frame = struct('FrameId', 1, 'ReceiverID', 'Rx1', 'ReceiverType', 'monitor', ...
    'Status', 'Success', 'SignalSources', {{source}});
payload = struct('Frames', {{{frame}}});
end
