classdef ReadAnnotationV2Test < matlab.unittest.TestCase
    %READANNOTATIONV2TEST Phase 6 annotation v2 reader contract.

    methods (Test)
        function validatesNestedFramesAndSummarizes(testCase)
            payload = localValidPayload();
            result = csrd.utils.annotation.readAnnotationV2(payload, ...
                'RequireSources', true, ...
                'RequireRuntimeHeader', true);

            testCase.verifyEqual(result.Summary.Schema, 'annotation-v2');
            testCase.verifyEqual(result.Summary.NumFrames, 1);
            testCase.verifyEqual(result.Summary.NumSources, 1);
            testCase.verifyEqual(result.Summary.NumReceivers, 1);
            testCase.verifyEqual(result.Summary.ReceiverIDs, {'Rx1'});
        end

        function readsJsonFile(testCase)
            payload = localValidPayload();
            path = localWriteTempJson(testCase, payload);

            result = csrd.utils.annotation.readAnnotationV2(path, ...
                'RequireSources', true);

            testCase.verifyEqual(result.Summary.SourcePath, path);
            testCase.verifyEqual(result.Summary.NumSources, 1);
        end

        function rejectsLegacyV1TopLevelFields(testCase)
            payload = localValidPayload();
            payload.Frames{1}{1}.SignalSources.Planned = struct();

            testCase.verifyError( ...
                @() csrd.utils.annotation.readAnnotationV2(payload), ...
                'CSRD:AnnotationV2:LegacyFieldPresent');
        end

        function rejectsMissingMeasuredFramePlane(testCase)
            payload = localValidPayload();
            payload.Frames{1}{1}.SignalSources.Truth.Measured = ...
                rmfield(payload.Frames{1}{1}.SignalSources.Truth.Measured, ...
                'FramePlane');

            testCase.verifyError( ...
                @() csrd.utils.annotation.readAnnotationV2(payload), ...
                'CSRD:AnnotationV2:MissingField');
        end

        function rejectsWrongMeasurementSemantics(testCase)
            payload = localValidPayload();
            payload.Frames{1}{1}.SignalSources.Truth.Measured.SourcePlane. ...
                MeasurementSemantics = 'execution_copy';

            testCase.verifyError( ...
                @() csrd.utils.annotation.readAnnotationV2(payload), ...
                'CSRD:AnnotationV2:UnexpectedSemantics');
        end

        function rejectsEmptyDesignTruth(testCase)
            payload = localValidPayload();
            payload.Frames{1}{1}.SignalSources.Truth.Design.ModulationFamily = '';

            testCase.verifyError( ...
                @() csrd.utils.annotation.readAnnotationV2(payload), ...
                'CSRD:AnnotationV2:InvalidDesignValue');
        end
    end
end


function payload = localValidPayload()
sourcePlane = struct( ...
    'OccupiedBandwidthHz', 1e6, ...
    'CenterFrequencyHz', 0, ...
    'SNRdB', 20, ...
    'TimeOccupancy', 1, ...
    'FrequencyOccupancy', 0.1, ...
    'MeasurementSemantics', 'receiver_view_isolated');

framePlane = struct( ...
    'OccupiedBandwidthHz', 1.2e6, ...
    'CenterFrequencyHz', 1e5, ...
    'TimeOccupancy', 1, ...
    'FrequencyOccupancy', 0.12, ...
    'MeasurementSemantics', 'post_rx_combined_pre_rfchain');

geometry = struct( ...
    'TxPositionM', [0 0 10], ...
    'TxVelocityMps', [1 0 0], ...
    'RxPositionM', [100 0 10], ...
    'LinkDistanceM', 100);

design = struct( ...
    'PlannedCenterFrequencyHz', 2.4e9, ...
    'PlannedBandwidthHz', 1e6, ...
    'PlannedSampleRate', 5e6, ...
    'ModulationFamily', 'QPSK', ...
    'ModulationOrder', 4, ...
    'PayloadLengthBits', 1024, ...
    'NumTransmitAntennas', 1);

execution = struct( ...
    'ModulatedBandwidthHz', 1e6, ...
    'CenterFrequencyOffsetHz', 0, ...
    'SampleRate', 5e6, ...
    'ChannelModel', 'AWGN', ...
    'PathLossDB', 80, ...
    'AnalyticalSNRdB', 20, ...
    'AppliedSNRdB', 20, ...
    'DopplerShiftHz', 1.5, ...
    'RadialVelocityMps', 0.2, ...
    'GeometrySnapshot', geometry);

source = struct( ...
    'TxID', 'Tx1', ...
    'SegmentId', 1, ...
    'BurstId', 'Burst1', ...
    'Truth', struct( ...
        'Design', design, ...
        'Execution', execution, ...
        'Measured', struct( ...
            'SourcePlane', sourcePlane, ...
            'FramePlane', framePlane)), ...
    'RFImpairments', struct(), ...
    'ReceiverView', struct( ...
        'ReceiverId', 'Rx1', ...
        'ProjectedCenterOffsetHz', 0, ...
        'ProjectedLowerEdgeHz', -5e5, ...
        'ProjectedUpperEdgeHz', 5e5, ...
        'IsVisible', true, ...
        'VisibilityReason', 'InBand'));

frame = struct( ...
    'FrameId', 1, ...
    'ReceiverID', 'Rx1', ...
    'Status', 'Success', ...
    'SignalSources', source);

payload = struct( ...
    'Frames', {{ {frame} }}, ...
    'Header', struct( ...
        'Runtime', struct( ...
            'BlueprintHash', 'abc123', ...
            'ValidatorVersion', 'phase6-test')));
end


function path = localWriteTempJson(testCase, payload)
tmpDir = tempname;
mkdir(tmpDir);
testCase.addTeardown(@() rmdir(tmpDir, 's'));
path = fullfile(tmpDir, 'annotation.json');
fid = fopen(path, 'w');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(payload));
delete(cleanup);
end
