classdef ReceiverViewObservableRangeContractTest < matlab.unittest.TestCase
    % ReceiverViewObservableRangeContractTest - Receiver view needs Rx range.

    methods (Test)
        function missingRangeIsRejected(testCase)
            spectrum = struct('PlannedBandwidth', 1e6, ...
                'PlannedFreqOffset', 0);
            rxConfigs = {struct('EntityID', 'Rx1')};

            testCase.verifyError(@() csrd.blocks.scenario ...
                .CommunicationBehaviorSimulator.projectReceiverViews( ...
                spectrum, rxConfigs, [-10e6, 10e6]), ...
                'CSRD:Scenario:MissingReceiverObservableRange');
        end

        function invalidRangeIsRejected(testCase)
            spectrum = struct('PlannedBandwidth', 1e6, ...
                'PlannedFreqOffset', 0);
            rx = struct('EntityID', 'Rx1', ...
                'Observation', struct('ObservableRange', [1e6, -1e6]));

            testCase.verifyError(@() csrd.blocks.scenario ...
                .CommunicationBehaviorSimulator.projectReceiverViews( ...
                spectrum, {rx}, [-10e6, 10e6]), ...
                'CSRD:Scenario:InvalidReceiverObservableRange');
        end
    end
end
