classdef ReceiveFactoryRxImpairmentsTest < matlab.unittest.TestCase
    % ReceiveFactoryRxImpairmentsTest
    %
    % Phase 1 / C1: ReceiveFactory.stepImpl must surface the FULL set of
    % RF impairments actually realised by RRFSimulator. Required fields
    % on receivedDataStruct.RxImpairments:
    %   Type, DCOffset, IqImbalanceConfig, ThermalNoiseConfig,
    %   MemoryLessNonlinearityConfig, SampleRateOffset.
    %
    % This test wires a minimal Hardware-receiver-type configuration
    % through ReceiveFactory and verifies the field set on the output.

    methods (Test)

        function emitsFullImpairmentSet(testCase)
            % Build a minimal Hardware-receiver-type recipe that exercises
            % the FULL impairment chain (DC offset, IQ imbalance, thermal
            % noise, memoryless nonlinearity). RRFSimulator.setupImpl
            % requires MemoryLessNonlinearityConfig to carry .Method (and
            % the matching method-specific fields), so we configure a
            % simple Cubic polynomial recipe with IIP3 specification.
            cfg = struct();
            cfg.Hardware = struct();
            cfg.Hardware.handle = 'csrd.blocks.physical.rxRadioFront.RRFSimulator';
            cfg.Hardware.DCOffset = [-60, -40];
            cfg.Hardware.IQImbalance = struct('Amplitude', [-1, 1], 'Phase', [-3, 3]);
            cfg.Hardware.ThermalNoise = struct('NoiseFigure', [3, 5]);
            cfg.Hardware.Nonlinearity = struct( ...
                'Methods', {{'Cubic polynomial'}}, ...
                'ReferenceImpedance', 50, ...
                'CubicPolynomial', struct( ...
                    'LinearGain', [10, 12], ...
                    'TOISpecifications', {{'IIP3'}}, ...
                    'IIP3',           [25, 35], ...
                    'OIP3',           [25, 35], ...
                    'IP1dB',          [25, 35], ...
                    'OP1dB',          [25, 35], ...
                    'IPsat',          [25, 35], ...
                    'OPsat',          [25, 35], ...
                    'AMPMConversion', [-1, 1], ...
                    'PowerLowerLimit', [-30, -20], ...
                    'PowerUpperLimit', [10, 20] ...
                ));

            factory = csrd.factories.ReceiveFactory('Config', cfg);
            % NOTE: we do NOT call release(factory) here because the
            % current ReceiveFactory.releaseImpl uses a non-existent
            % built-in `hasMethod` (a pre-existing defect outside the
            % scope of Phase 1, tracked for a later phase). Avoiding the
            % release call lets this Phase 1 contract test run cleanly
            % until the pre-existing release bug is fixed.

            rxInfo = struct('NumAntennas', 1, 'SampleRate', 20e6, ...
                'ID', 'Rx1', 'EntityID', 'Rx1');
            recvScenario = struct('ID', 'Rx1', 'EntityID', 'Rx1', 'Type', 'Hardware');
            inputSig = struct('Signal', complex(zeros(64, 1)), ...
                'SampleRate', 20e6, 'ID', 1, 'TxId', 'Tx1', 'BurstId', 'Tx1.B0');

            out = step(factory, inputSig, 1, rxInfo, recvScenario);

            testCase.verifyTrue(isfield(out, 'RxImpairments'), ...
                'receivedDataStruct must contain an RxImpairments field.');
            imp = out.RxImpairments;
            for fn = {'Type', 'DCOffset', 'IqImbalanceConfig', ...
                    'ThermalNoiseConfig', 'MemoryLessNonlinearityConfig', ...
                    'SampleRateOffset'}
                testCase.verifyTrue(isfield(imp, fn{1}), ...
                    sprintf('RxImpairments.%s must be present (Phase 1 full set).', fn{1}));
            end
            testCase.verifyEqual(imp.Type, 'Hardware', ...
                'RxImpairments.Type must record the receiver-type recipe used.');
            testCase.verifyTrue(isnumeric(imp.SampleRateOffset) && isreal(imp.SampleRateOffset), ...
                'RxImpairments.SampleRateOffset must be a real numeric scalar.');
            testCase.verifyTrue(isstruct(imp.MemoryLessNonlinearityConfig), ...
                'RxImpairments.MemoryLessNonlinearityConfig must be a struct.');
            testCase.verifyTrue(isfield(out, 'Signal'), ...
                'receivedDataStruct must carry the processed Signal.');
        end

    end

end
