classdef RegulatoryValidatorTest < matlab.unittest.TestCase
    %REGULATORYVALIDATORTEST Phase 8 regulatory fail-fast tests.

    methods (Test)
        function rejectsRadarBand(testCase)
            band = localValidBand();
            band.ServiceClass = 'Radiolocation';
            testCase.verifyError( ...
                @() csrd.utils.spectrum.RegulatoryValidator.validateBand(band), ...
                'CSRD:Spectrum:ExcludedServiceClass');
        end

        function rejectsOutOfBandSelection(testCase)
            catalog = csrd.utils.spectrum.RegionSpectrumCatalog.load('CN');
            receiver = struct('CenterFrequencyHz', 100e6, 'SampleRateHz', 50e6);
            plan = struct( ...
                'RegionId', 'CN', ...
                'BandId', 'CN_FM_BROADCAST', ...
                'SelectedCenterFrequencyHz', 120e6, ...
                'BandwidthHz', 200e3, ...
                'ModulationFamily', 'FM', ...
                'Regulatory', csrd.utils.spectrum.RegulatoryValidator.emptyRegulatoryTruth());
            testCase.verifyError( ...
                @() csrd.utils.spectrum.RegulatoryValidator.validateEmitterPlan(plan, catalog, receiver), ...
                'CSRD:Spectrum:SelectionOutOfBand');
        end

        function rejectsIllegalModulationForService(testCase)
            catalog = csrd.utils.spectrum.RegionSpectrumCatalog.load('CN');
            receiver = struct('CenterFrequencyHz', 100e6, 'SampleRateHz', 50e6);
            plan = struct( ...
                'RegionId', 'CN', ...
                'BandId', 'CN_FM_BROADCAST', ...
                'SelectedCenterFrequencyHz', 100e6, ...
                'BandwidthHz', 200e3, ...
                'ModulationFamily', 'QAM', ...
                'Regulatory', csrd.utils.spectrum.RegulatoryValidator.emptyRegulatoryTruth());
            testCase.verifyError( ...
                @() csrd.utils.spectrum.RegulatoryValidator.validateEmitterPlan(plan, catalog, receiver), ...
                'CSRD:Spectrum:IllegalModulationForService');
        end

        function acceptsValidFmSelection(testCase)
            catalog = csrd.utils.spectrum.RegionSpectrumCatalog.load('CN');
            receiver = struct('CenterFrequencyHz', 100e6, 'SampleRateHz', 50e6);
            plan = struct( ...
                'RegionId', 'CN', ...
                'BandId', 'CN_FM_BROADCAST', ...
                'SelectedCenterFrequencyHz', 100e6, ...
                'BandwidthHz', 200e3, ...
                'ModulationFamily', 'FM', ...
                'Regulatory', csrd.utils.spectrum.RegulatoryValidator.emptyRegulatoryTruth());
            testCase.verifyWarningFree( ...
                @() csrd.utils.spectrum.RegulatoryValidator.validateEmitterPlan(plan, catalog, receiver));
        end
    end
end


function band = localValidBand()
catalog = csrd.utils.spectrum.RegionSpectrumCatalog.load('CN');
band = catalog.Bands(1);
end
