classdef TRFExactResampleContractTest < matlab.unittest.TestCase
    % TRFExactResampleContractTest - TRF must not emit wrong sample rates.

    methods (Test)
        function exactRatioRunsWarningFree(testCase)
            trf = csrd.blocks.physical.txRadioFront.TRFSimulator( ...
                'SampleRate', 42e6, ...
                'TargetSampleRate', 50e6, ...
                'CarrierFrequency', 0, ...
                'BandWidth', 1e6, ...
                'TxPowerDb', 0, ...
                'DCOffset', -100, ...
                'IqImbalanceConfig', struct('A', 0, 'P', 0), ...
                'PhaseNoiseConfig', struct('Level', -100, ...
                    'FrequencyOffset', 10e3), ...
                'MemoryLessNonlinearityConfig', localNlConfig());
            cleanupObj = onCleanup(@() release(trf)); %#ok<NASGU>

            out = testCase.verifyWarningFree(@() step(trf, ones(420, 1)));
            testCase.verifyGreaterThan(numel(out), 420);
        end
    end
end

function cfg = localNlConfig()
cfg = struct('Method', 'Cubic polynomial', ...
    'LinearGain', 0, ...
    'TOISpecification', 'IIP3', ...
    'IIP3', 30, ...
    'AMPMConversion', 0, ...
    'PowerLowerLimit', -50, ...
    'PowerUpperLimit', 10, ...
    'ReferenceImpedance', 50);
end
